### ISSUE TITLE
[suggestion] examples.

### ISSUE THREAD

**Issue by aGingerThing** [TheIllusiveC4/VeinMining#10]
I have noticed there are a lot of people saying things like "how do I get it to only work on ores" or "how do I stop it from working on stone".

I think it would be really helpful if you just added an example block to the whitelist/blacklist section or you could even add presets like ores only or trees only.

**Comment by TheIllusiveC4** [comment]
I can't really add anything to the list themselves, otherwise it'll apply the behavior automatically. All I can do is maybe add something to the comments, or make a wiki page with some examples.

**Comment by TheIllusiveC4** [comment]
I've added a wiki page about the configuration and provided an example for "ores only".

**Comment by aGingerThing** [comment]
cool that'll probably do
