### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jaynotgay** [TheIllusiveC4/VeinMining#100]
### Minecraft Version

1.19.2

### What happened?

When players use vein mining, the server freezes. The combination of vein mining and the auto smelting pickaxe from Twilight Forest  almost causing the server to crash.

### How do you trigger this bug?

Use the enchantment.

### Loader

Fabric

### Loader Version

Fabric 

### API Version

fabric-server-mc.1.19.2-0.11.2

### Mod Version

veinmining-fabric-1.1.1+1.19.2

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, loading up both Vein Mining and Twilight Forest doesn't cause any issues with vein mining. Does this happen with _only_ Vein Mining and Twilight Forest installed? Does this happen in single-player or only on a multiplayer server? Can you share any logs from these freezes?
