### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xoltrain** [TheIllusiveC4/VeinMining#101]
### Minecraft Version

1.20.1

### What happened?

Weather in hardcore or regular survival with cheats enabled, the veinminer enchantment on a book will not allow me to put on any tools, i am using the most recent 1.20.1 version. However in creative it works just fine, anyway to get around this? Also tried to put multiple enchantment books together combined with the veinminer to see if that would work and all it did was get rid of the veinminer at the end.

### How do you trigger this bug?

1.Put an anvil down
2.Gave myself levels, a veinminer enchantment book, and a diamond pickaxe
3.Tried to combine the veinminer with the diamond pickaxe and was restricted to do so
...

### Loader

Fabric

### Loader Version

Fabric 0.14.21-1.20.1

### API Version

Fabric api 0.86.0-1.20.1

### Mod Version

1.20.0+1.20.1

**Comment by TheIllusiveC4** [comment]
I tried this myself and it works fine for me. Have you tried this with _just_ Vein Mining installed? If not, try it and see if it's due to a mod conflict.
