### ISSUE TITLE
[Suggestion]: Vein mining shape control

### ISSUE THREAD

**Issue by DakotaJM-git** [TheIllusiveC4/VeinMining#105]
### What is the new feature or improvement?

I've seen in older vein mining mods the ability to contain the enchantment to only mine within certain parameters. Being able to control the ending shape to some degree would be favorable.

Example: 
Containing the enchantment to mine 50 blocks, within a radius-length of 2-0 (0 being the identifier for infinite) from the source block. 

This would contain the ability to create a 5x5 tunnel extending in infinitely until 50 block maximum. 

The direction of the newly formed tunnel would be controlled by the direction the player is trying to mine but restricted to the 4-cardinal direction + up and down. 

Further development may include dynamic directionality of diagonals.

**Comment by TheIllusiveC4** [comment]
I don't have any plans to make the vein mining more complex in this manner. I like keeping the implementation fairly basic, it just mines the nearest connected blocks and that's all. Introducing any level of shape control drastically increases the overhead of the mod, it would likely at least need a GUI to manage and edit the shape and I think that drifts away from the spirit of the mod being a lightweight and straightforward approach to vein mining.

I'd be happy to hear any more arguments for this feature, but for now I don't have any plans for its inclusion.
