### ISSUE TITLE
[Bug]: Latest version on CurseForge for 1.19.3 is actually for 1.19.4

### ISSUE THREAD

**Issue by Qsta981** [TheIllusiveC4/VeinMining#106]
### Minecraft Version

1.19.2

### What happened?

This is on 1.19.3, not 1.19.2, and the latest version is for 1.19.4, not 1.19.3

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric - compatible (fabric is not the issue)

### API Version

Fabric API 0.76.1

### Mod Version

Vein Mining 1.1.2 1.19.4 (Listed for 1.19.3)

**Comment by TheIllusiveC4** [comment]
Hm, weird. It does technically work with 1.19.3, but the build output lists it at 1.19.4 for some reason. Maybe an artifact from development that I forgot about. Anyway, removed the 1.19.3 version listing which should default to the previous 1.19.3 build.
