### ISSUE TITLE
[Bug]: it not working in the modpack Prominence II [FORGE]

### ISSUE THREAD

**Issue by Phromphithak** [TheIllusiveC4/VeinMining#109]
### Minecraft Version

1.20.1

### What happened?

when i enchant VeinMining in fabric modpack it work perfeactly fine 
when i come play the Forge it not work?
By default it setting stand mine for activate but it not working.
i try the config but it not work all the way.
i mine the gold diamon copper it not work

### How do you trigger this bug?

1.idk
2.
3.
...

### Loader

Forge

### Loader Version

Forge - 47.1.3

### API Version

Forge - 47.1.3

### Mod Version

latest

**Comment by TheIllusiveC4** [comment]
1. Share your configuration files.
2. Are you using it enchanted or non-enchanted?
3. What blocks have you tried it on, and with what tools?

**Comment by h1deto** [comment]
I have the same issue.

Un-altered config files, deleted config files and the mod, re-downloaded mod and then started the modpack.

Have tried both the enchanted and non-enchanted settings.

Tried it on most blocks I could find in a five minute run-a-round in a newly made survival world. Tried with different tools. Neither vanilla Minecraft tools nor modded work. (I was in survival mode and not in creative mode when trying the mod.)

The enchantment shows up, in game, both in enchanting table and in villager trading. 

Just the veinmining part of it doesn't seem to be working at all.

Forge version is 47.1.3.

Are there any dependencies for this mod?

**Comment by h1deto** [comment]
After some troubleshooting, I found the problem. In the modpack there's a mod called [HT's TreeChop](https://www.curseforge.com/minecraft/mc-mods/treechop).

It causes the veinmining part of your mod to not work at all.

Disabling this mod fixes the issue.

**Comment by Phromphithak** [comment]
i goanna try that thank.
Edit: It works fine perfectly after delete the tree chopper
> After some troubleshooting, I found the problem. In the modpack there's a mod called [HT's TreeChop](https://www.curseforge.com/minecraft/mc-mods/treechop).
> 
> It causes the veinmining part of your mod to not work at all.
> 
> Disabling this mod fixes the issue.
