### ISSUE TITLE
[Bug]: Apotheosis and Vein Mining conflict

### ISSUE THREAD

**Issue by maxiboy211** [TheIllusiveC4/VeinMining#112]
### Minecraft Version

1.20.1

### What happened?

There is some weird interaction between [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) and [Vein Mining](https://www.curseforge.com/minecraft/mc-mods/vein-mining).
Installing Apoth changes something about the enchantment and makes it ignore the config set options. Setting the enchant to have e.g. 4 levels in the config doesn't do anything. The name of the enchant in game does change, 1 max level is "Vein Mining" and setting that to ≥2 changes it to "Vein Mining X".
Only level 1 is obtainable through villager trading, enchanting or commands. Combining the level 1 books in an anvil yields another level 1 book. Using **/enchant** returns the usual error when trying to set a wrong level - _[CHAT] 3 is higher than the maximum level of 1 supported by that enchantment_. Disabling just Apotheosis fixes this issue.
Vein Mining book is also not displaying in JEI when searching for "vein" but vanilla enchants do when typing e.g. "unbrea" for Unbreaking (tested with just JEI and Vein Mining).

<details>
    <summary>Mod list:</summary>
    
    Apotheosis-1.20.1-7.0.5
    ApothicAttributes-1.20.1-1.1.4
    Jade-1.20.1-forge-11.6.3
    jei-1.20.1-forge-15.2.0.27
    Placebo-1.20.1-8.3.7
    veinmining-forge-1.2.1+1.20.1
</details>

I can open an issue on [Apoth's github](https://github.com/Shadows-of-Fire/Apotheosis) and link it to here if needed.

### How do you trigger this bug?

1. Install Vein Mining and Apotheosis(+dependencies)
2. Set the max level of Vein Mining to anything greater than 1
3. The enchant(level 2 or higher) is not obtainable in game

### Loader + Version

Forge 47.2.4

### Mod Version

veinmining-forge-1.2.1+1.20.1

**Comment by TheIllusiveC4** [comment]
Is this in a single player instance or on a multiplayer server?

**Comment by maxiboy211** [comment]
Singleplayer.

**Comment by SiverDX** [comment]
did you check the apotheosis config file?
i can imagine it having problems when the returned value is a config value which may or may not be ready/set yet

in that case the maximum level could be 1 in the apotheosis config
generally configs from mods dont apply with apotheosis present, maximum value for all cases are handled through its config file

**Comment by maxiboy211** [comment]
Had no idea Apoth had that much control over enchants, let alone modded ones. Setting up the Apoth config properly does fix everything mentioned, thank you! Anyone trying to do the same, go into \config\apotheosis and open enchantments.cfg. Search for _veinmining:vein_mining_ and edit the first 2 options, **I:"Max Level"=x** and **I:"Max Loot Level"=x**. Set the max level to what you have in your veinmining-common file and the wanted max level in loot tables.
