### ISSUE TITLE
[Bug]: HT's TreeChop conflict

### ISSUE THREAD

**Issue by PatrickPichler98** [TheIllusiveC4/VeinMining#113]
### Minecraft Version

1.20.1

### What happened?

Hello when i install Vein Mining and HT's TreeChop, the Enchant don't work anymore  :/

### How do you trigger this bug?

1. install HT's TreeChop
2.
3.
...

### Loader

Forge

### Loader Version

Forge 47.2.4

### Mod Version

Vein Mining 1.2.1+1.20.1

**Comment by TheIllusiveC4** [comment]
This has been addressed on HT's TreeChop's end as of their version 0.18.7 and above.
