### ISSUE TITLE
[Bug]: Vein Mining Book Turns into Blank Enchanted Book upon entering Player Inventory

### ISSUE THREAD

**Issue by InfamyFX** [TheIllusiveC4/VeinMining#117]
### Minecraft Version

1.20.2

### What happened?

I installed the mod on both my Server and my Client and then joined, set myself in Creative and looked for "Vein" in the Creative Inventory, found the Book and thought it all worked, so I gave myself 3 Books, 1 for each of our 3 Members, but after going into the Anvil and trying to put them on the Pickaxe, they turned into blank Enchanted Books when before they said Enchanted Book, Ingredients, Vein Miner.

### How do you trigger this bug?

1.Creative
2.Grab Vein Miner Book
3.Open Normal Inventory
...

### Loader

Fabric

### Loader Version

Fabric 0.15.3

### API Version

Fabric API 0.91.2+1.20.2

### Mod Version

Vein Mining Fabric 2.1.0+1.20.2

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this using the versions you listed, the enchantment books that I obtain from Creative can then be used in the Anvil as expected and do not become blank.

If you used this with other mods, please try testing this with _only_ Vein Mining and Fabric API to see if it's potentially a mod conflict.
