### ISSUE TITLE
[Bug]: activation key configuration is wiped out every time launching the game with client `maxBlocksBase` set to 0

### ISSUE THREAD

**Issue by RocketMaDev** [TheIllusiveC4/VeinMining#118]
### Minecraft Version

1.20.2

### What happened?

> I always played on a server which have veinmining-server installed and `maxBlocksBase` set
(in remote `veinmining-server.toml`) , and I had the mod in my client. I don't play standlone saves.

tl;dr: Every time I launched the game and entered the server, I found myself setting the activation key again.

Later I checked the mod and found that when I set up activation key in a standlone save, it says it's not enabled in config. So I restarted the game, but this time, I had `maxBlocksBase`(in local `veinmining-server.toml`) set. To my surprise, my activation key can be kept now.

Apparently, the mod only keeps activation key when `maxBlocksBase` is set, which is reasonable in standlone mode. But when a player only plays on servers, the bug appears.

### How do you trigger this bug?

1. set `maxBlocksBase` to 0 in client config
2. launch the game and enter a supported server with `maxBlocksBase` set in server config
3. set an activation key
4. restart the game, activation key lost

(Actually in a `maxBlocksBase` set server, when set up activation key, *(Disabled by Configuration)* is replaced with *Activate*,
making the bug harder to trace.)

### Loader

Fabric

### Loader Version

0.15.0

### API Version

0.91.1

### Mod Version

2.1.0

**Comment by mmalfatti** [comment]
I'm using single player mode running 1.20.1.  No matter what I do to the config files they are overwritten.  Any thoughts?

**Comment by TheIllusiveC4** [comment]
@mmalfatti Please create your own issue report to discuss that problem as it seems to be a separate issue from this one.
