### ISSUE TITLE
[Feature]: Option for vein mining stone-type blocks

### ISSUE THREAD

**Issue by krjencik** [TheIllusiveC4/VeinMining#120]
### What is the new feature or improvement?

It would be great if in my singleplayer world i could vein mine stone, deepslate  and other stones...
simply said all blocks except chests and these things... 

Its great when vein mining a certain type of block (for example coal ore) only the connected blocks of the certain type is destroyed (only the coal ore)

**Comment by TheIllusiveC4** [comment]
You can already configure it to mine stone, just make sure to edit the `blocksList` and `blocksListType` in the `veinmining-server.toml` configuration file according to your needs. In your case, you may want to make sure that `#minecraft:stone` is in there for all blocks in that tag.

**Comment by krjencik** [comment]
ty thats what i needed to know :)
