### ISSUE TITLE
[Bug]: Config seems not work propertly

### ISSUE THREAD

**Issue by daordonep** [TheIllusiveC4/VeinMining#121]
### Minecraft Version

1.20.4

### What happened?

I have configured the mod to remove sand and gravel but it doesn't seem to work. Its a server.
`blocks = "CONFIG_LIST"
#The blocks or block tags for vein mining if blocks is set to "CONFIG_LIST".
blocksList = ["#c:ores", "#forge:ores", "#minecraft:logs"]
#Determines if blocksList contains allowed blocks or denied blocks.
#Allowed Values: ALLOW, DENY
blocksListType = "ALLOW"
#The groups of blocks or block tags that are vein mined together.
groupsList = ["#forge:obsidian", "#forge:ores/coal", "#forge:ores/diamond", "#forge:ores/emerald", "#forge:ores/gold", "#forge:ores/iron", "#forge:ores/lapis", "#forge:ores/redstone", "#forge:ores/quartz", "#forge:ores/netherite_scrap", "#forge:ores/copper", "#forge:ores/tin", "#forge:ores/osmium", "#forge:ores/uranium", "#forge:ores/fluorite", "#forge:ores/lead", "#forge:ores/zinc", "#forge:ores/aluminum", "#forge:ores/nickel", "#forge:ores/silver", "#forge:ores/apatite", "#forge:ores/cinnabar", "#forge:ores/niter", "#forge:ores/ruby", "#forge:ores/sapphire", "#forge:ores/sulfur", "#forge:sand", "#forge:gravel", "#minecraft:sand", "#minecraft:gravel"]`

### How do you trigger this bug?

Configure veinmining-server.toml.
Restart server
test it.

### Loader

NeoForge

### Loader Version

NeoForge 20.4.218

### Mod Version

Vein Mining neo Forge 3.1.0 +1.20.4 jar

**Comment by TheIllusiveC4** [comment]
You seem to have placed your entries into the wrong list. You put your sand and gravel entries into the `groupsList`, when it should have been added into the `blocksList`.

**Comment by daordonep** [comment]
works perfectly! thank you!
