### ISSUE TITLE
[Bug]: Not Working on Forge 1.20.1 client

### ISSUE THREAD

**Issue by V-Tom** [TheIllusiveC4/VeinMining#122]
### Minecraft Version

1.20.1

### What happened?

> single player mode not on server side

It not working on client survival mode with normal tools, tired the `STANDING` , `CROUCHING ` event setup `HOLD_KEY_DOWN`, but it works well if tools with the enchantment on survival mode.

Here is the config for `veinmining-client.toml`
```
#If maxBlocksBase is 0, determines how to activate vein mining.
#Allowed Values: STANDING, CROUCHING, HOLD_KEY_DOWN
activationState = "STANDING"
#If maxBlocksBase is greater than 0, determines how to activate vein mining.
#Allowed Values: STANDING, CROUCHING, HOLD_KEY_DOWN
activationStateWithoutEnchantment = "CROUCHING"
```

Others all default without any change on client.

- veinmining-common.toml
- veinmining-server.toml

Here is the screenshot all mods installed, not sure if something conflicted, thank you.

![image](https://github.com/illusivesoulworks/veinmining/assets/8033489/30cf5517-5de8-484c-afee-9b47113b0d30)

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

forge 47.2.0

### Mod Version

veinmining-forge-1.4.0+1.20.1

**Comment by V-Tom** [comment]
The tools must with the enchantment could be works well?

**Comment by TheIllusiveC4** [comment]
If the `veinmining-server.toml` is default, then that means you need the enchantment on the tool in order to work. You need to increase the `maxBlocksBase` field in that configuration file in order to utilize vein mining without the enchantment.
