### ISSUE TITLE
[Bug]: Vein mining not working on server 1.20.1

### ISSUE THREAD

**Issue by lolpowerluke** [TheIllusiveC4/VeinMining#124]
### Minecraft Version

1.20.1

### What happened?

enchatment doesnt work
![image](https://github.com/illusivesoulworks/veinmining/assets/47672899/3c87b00b-1af6-479f-b51a-63205e084c12)
tried mining with this pickaxe, but it only mines 1 block at a time
idk if it matters, but I enchanted it unsing the blaze enchanters from create enchantment industry

### How do you trigger this bug?

1. idk tbh

### Loader

Forge

### Loader Version

47.2.17

### Mod Version

1.4.0+1.20.1

### Relevant Log Outputs

idk if relevant, but here is my server log
[latest.log](https://github.com/illusivesoulworks/veinmining/files/15082401/latest.log)
and here is the client log
[latest.log](https://github.com/illusivesoulworks/veinmining/files/15082438/latest.log)

**Comment by TheIllusiveC4** [comment]
How are you using the enchanted tool?

Can you share your client's `veinmining-client.toml` and the server's `veinmining-server.toml` configuration?

**Comment by lolpowerluke** [comment]
[veinmining-client.txt](https://github.com/illusivesoulworks/veinmining/files/15098417/veinmining-client.txt)
[veinmining-server.txt](https://github.com/illusivesoulworks/veinmining/files/15098418/veinmining-server.txt)
here u go, renamed both to .txt bc github doesnt accept .toml

**Comment by TheIllusiveC4** [comment]
Hm, okay, so based on your configuration you should be able to vein mine ores and logs by enchanting your tool with Vein Mining. Which blocks have you tested it on?

**Comment by lolpowerluke** [comment]
netherrack, stone and cobblestone

**Comment by lolpowerluke** [comment]
well I just tried it on zinc (a create ore) since you asked which blocks and it worked for that, any reason why it doesnt work for the above 3?

**Comment by TheIllusiveC4** [comment]
Netherrack, stone, and cobblestone are not considered ores and logs, and your configuration is set to only vein mine ores and logs.

**Comment by lolpowerluke** [comment]
I see, I also found what you mean in the config, ty
