### ISSUE TITLE
[Bug]: Configuration does not work for our modded ores

### ISSUE THREAD

**Issue by Zanklev** [TheIllusiveC4/VeinMining#128]
### Minecraft Version

1.20.1

### What happened?

No matter how I setup the config file, vein mining will not work for any modded ores. I'm trying to add the new ores from "Just Enough Guns" / JEG

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Forge 47.2.0

### Mod Version

veinmining-forge-1.4.1+1.20.1

### Relevant Log Outputs

#If enabled, vein mining will move drops from blocks to the source location.
relocateDrops = true
#If enabled, vein mining will never break tools.
preventToolDestruction = true
#If enabled, vein mining will damage the tool for each block mined.
addToolDamage = true
#The multiplier to tool damage from blocks that are vein mined.
#Range: 0 ~ 1000
toolDamageMultiplier = 1
#If enabled, vein mining will cause player exhaustion for each block mined.
addExhaustion = true
#The multiplier to player exhaustion from blocks that are vein mined.
#Range: 0.0 ~ 1000.0
exhaustionMultiplier = 1.0
#Determines the vein mineable blocks based on a preset option or a configured list.
#Allowed Values: CONFIG_LIST, ALL, ORES, ORES_LOGS, ORES_STONE, ORES_STONE_LOGS, NO_BLOCK_ENTITIES
blocks = "CONFIG_LIST"
#The blocks or block tags for vein mining if blocks is set to "CONFIG_LIST".
blocksList = ["#c:ores", "#forge:ores", "#minecraft:logs", "#JEG:scrap_ore", "#JEG:deepslate_scrap_ore", "#JEG:brimstone_ore", "#JEG:blackstone_brimstone_ore", "#JEG:basalt_brimstone_ore"]
#Determines if blocksList contains allowed blocks or denied blocks.
#Allowed Values: ALLOW, DENY
blocksListType = "ALLOW"
#The groups of blocks or block tags that are vein mined together.
groupsList = ["#forge:obsidian", "#forge:ores/coal", "#forge:ores/diamond", "#forge:ores/emerald", "#forge:ores/gold", "#forge:ores/iron", "#forge:ores/lapis", "#forge:ores/redstone", "#forge:ores/quartz", "#forge:ores/netherite_scrap", "#forge:ores/copper", "#forge:ores/tin", "#forge:ores/osmium", "#forge:ores/uranium", "#forge:ores/fluorite", "#forge:ores/lead", "#forge:ores/zinc", "#forge:ores/aluminum", "#forge:ores/nickel", "#forge:ores/silver", "#forge:ores/apatite", "#forge:ores/cinnabar", "#forge:ores/niter", "#forge:ores/ruby", "#forge:ores/sapphire", "#forge:ores/sulfur"]

**Comment by TheIllusiveC4** [comment]
> blocksList = ["#c:ores", "#forge:ores", "#minecraft:logs", "#JEG:scrap_ore", "#JEG:deepslate_scrap_ore", "#JEG:brimstone_ore", "#JEG:blackstone_brimstone_ore", "#JEG:basalt_brimstone_ore"]

I'm not sure this is correct. Are you trying to add blocks or tags? The `#` is only needed for tags and, as far as I can tell, the JEG mod does not have these tags.

**Comment by Zanklev** [comment]
I tried without the tags as well, I was just trying different methods of adding the ores into the text file. The ores I'm trying to mine just show as "JEG:scrap_ore" when looking at them with F3 or with expanded tooltips enabled. With or without the # it doesn't work.

**Comment by TheIllusiveC4** [comment]
Have you tried `jeg:scrap_ore`? Lowercased instead of upper? Also, are you editing this while in-game?

**Comment by Zanklev** [comment]
I first tried ingame, then restarted. I also tried editing the file myself outside of the game. I haven't tried lowercase so I'll try that real quick.

**Comment by Zanklev** [comment]
Oh good lord, ya making JEG lowercase fixed it and it's working now. Alright thank you lol.
