### ISSUE TITLE
[Bug]:The Vein Mining enchantment book does not exist

### ISSUE THREAD

**Issue by asnndpro** [TheIllusiveC4/VeinMining#130]
### Minecraft Version

1.20.6

### What happened?

I used Vein Mining Mod when creating the integration package today, but there was an issue with it. While testing the Mod function, I found that there was no Vein Mining enchantment book in the item list of the creation mode. However, it can also use enchantment tables and purchase related enchantment books through villagers. After realizing this bug, I tested this Mod in both Fabric and Forge, and no surprise, this problem occurred. When I was suitable for using this mod in version 1.20.1, this issue did not occur.

### How do you trigger this bug?

1.Open creation mode
2.Press E
3.Find the Vein Mining enchantment book
4.The Vein Mining enchantment book does not exist
...

### Loader

Fabric

### Loader Version

fabri0.15.11/fabri-api0.99.4

### API Version

fabri-api0.99.4

### Mod Version

Vein Mining4.0.1+1.20.6

**Comment by maugwei** [comment]
I am also having this issue.
