### ISSUE TITLE
[Bug]: Can't vein mine stone/deepslate

### ISSUE THREAD

**Issue by Water3284** [TheIllusiveC4/VeinMining#131]
### Minecraft Version

1.20.1

### What happened?

I wanted to be able to vein mine stone, tried it myself for a while and gave up. I went here and found someone with a similar issue and tried their solution (putting #minecraft:stone into the vein mining blocks list) but it didnt work, if someone could tell me how to do this properly I would greatly appreciate it.

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric - 0.15.11

### API Version

???

### Mod Version

Vein mining-fabric-1.3.1

**Comment by TheIllusiveC4** [comment]
Try putting just `"minecraft:stone"` in the blocks list, without the hash tag.

**Comment by Water3284** [comment]
> Try putting just `"minecraft:stone"` in the blocks list, without the hash tag.

It didn't work, also nice response time! :) do u have anything else that might work?

**Comment by TheIllusiveC4** [comment]
How are you adding it in? Through the in-game config or the config files directly? If you're making changes in-game, have you tried reloading the world to test?

Also, please share your configuration after your changes so I can verify the values.

**Comment by Water3284** [comment]
I got it, i just needed to reload my world lol, idk why i didnt think of that, thanks for the help!!! :D

**Comment by TheIllusiveC4** [comment]
You're welcome, happy to help.
