### ISSUE TITLE
[Crash]: Not compatible with NoShieldDelay

### ISSUE THREAD

**Issue by Phoupraw** [TheIllusiveC4/VeinMining#132]
### Minecraft Version

1.21.0

### What happened?

Game crashes on launching. Game doesn't crash only NoShieldDelay enabled.

### How do you trigger this bug?

1. Install NoShieldDelay.
2. Install this mod.
3. Launch game.
4. Crash.

### Loader

Fabric

### Loader Version

0.15.11

### API Version

0.100.4

### Mod Version

5.0.0-beta+1.21

### Relevant Log Outputs

https://pastebin.com/7YMVzr1f

**Comment by TheIllusiveC4** [comment]
This is not a Vein Mining issue, as this occurs with other mods and No Shield Delay:

https://github.com/Quplet/NoShieldDelay/issues/2
