### ISSUE TITLE
It wont activate for me. 1.16.4

### ISSUE THREAD

**Issue by RepoDraghon** [TheIllusiveC4/VeinMining#14]
I'm sorry if this has been mentioned before, I tried a search but didn't see it. I added this to what is technically the Direwolf20 1.16 pack but since it's not on the CurseForge app and only on the FTB app, I found all the mods and just created the mod pack on Curse...
I know the mod is designed for 1.16.5 but I have other mods that are for 1.16.5 that work on 1.16.4 so this isn't really I want this fixed as much as it's just informing you that the mod is a valid mod, just not working...

Stock it was set to STANDING, I changed it to CROUCHING, no go...
Tried KEYBINDING, no go...
Tried deleting the config file to refresh, no go...

**Comment by TheIllusiveC4** [comment]
Did you make sure the tool was enchanted with Vein Mining when you tested it?

**Comment by RepoDraghon** [comment]
I didn't realize this was not the typical Veinminer by Portablejim that I use... Sorry, yes, I was not using the enchant...
