### ISSUE TITLE
[Suggestion] Quark compatability

### ISSUE THREAD

**Issue by DSchougaard** [TheIllusiveC4/VeinMining#15]
Hello

Would it be possible to make the enchant appliable to the Pickarang from the Quark mod?

**Comment by DSchougaard** [comment]
For what it's worth, a Pickarang can be spawned in with the enchantment using commands and it appears to be working as expected.

Command:
/give @p quark:pickarang{Enchantments:[{id:"veinmining:vein_mining",lvl:1}]} 1

**Comment by TheIllusiveC4** [comment]
Yeah, looking at the source code for the Pickarang, I believe everything should work fine. I just need to make it a valid item for the enchantment. Possibly as a config option for additional valid items.

**Comment by Guernica520** [comment]
I would also love this feature to be added to the pickerang
