### ISSUE TITLE
Suggestion: Make the config file be common instead of server-side

### ISSUE THREAD

**Issue by Foozey** [TheIllusiveC4/VeinMining#17]
This would avoid the need to keep re-editing it or copying and pasting a previously edited one every time that a new world is created.

**Comment by TheIllusiveC4** [comment]
That's what the `defaultconfigs` folder is for. You copy and paste the server config file you want into it and it will copy that one into new worlds instead of generating a new one.

**Comment by Foozey** [comment]
Oh true... forgot about that. Sorry, was tired lol.
