### ISSUE TITLE
Changes won't save.

### ISSUE THREAD

**Issue by Gohirro** [TheIllusiveC4/VeinMining#19]
For some reason, the veinmining-client.toml file keeps getting reverted/overwritten to default values, even when saving changes without minecraft (or the launcher) open. How do I add the configs to blacklist stone from being mined up? I can't seem to figure out why it will not keep the saved settings/changes.

**Comment by Gohirro** [comment]
Here is how the config file is written when I save it:

["vein mining"]
	#Whether to activate vein mining by standing, crouching, or holding down the keybind
	#Allowed Values: STANDING, CROUCHING, KEYBINDING
	activationState = "STANDING"
	blocks = ["#forge:ores"]
	blocksPermission = "WHITELIST"

**Comment by TheIllusiveC4** [comment]
Have you confused the `veinmining-client.toml` file with the `veinmining-server.toml` file in your world save's `serverconfigs` folder? The latter is what you need to edit in order to change block permissions. Trying to add values to the former will reset them because that's not what the client config is used for.

**Comment by Gohirro** [comment]
The only file is the client one, its the one I am trying to edit. This is in the root config folder: veinmining-client.toml.

**Comment by Gohirro** [comment]
Okay, so I found the problem. I hosted my SP game over LAN to do some testing with once. I just edited the server config file and sure enough, that did the trick. So I guess that it is using the server file even though its single player for some reason.

**Comment by Gohirro** [comment]
Oh wait, you already mentioned that. Thanks for the quick reply.
