### ISSUE TITLE
Config file keeps getting overriden

### ISSUE THREAD

**Issue by revdave33** [TheIllusiveC4/VeinMining#20]
veinmining-fabric-0.0.8-1.17
Fabric 0.11.3

I try to make some configuration changes in the config/veinmining.json5 and when I start up Fabric, my changes get overriden so I am unable to make any configuration changes.

**Comment by TheIllusiveC4** [comment]
I can't reproduce this, the configuration file works fine for me. What's your modlist? Do you have Cloth Config installed?

**Comment by revdave33** [comment]
Yes, I do. Cloth config 5.0.34

**Comment by TheIllusiveC4** [comment]
What does your configuration file look like? When you edit it, before it gets overridden.

**Comment by revdave33** [comment]
It was fixed on the latest updates
