### ISSUE TITLE
Config doesnt save

### ISSUE THREAD

**Issue by OneWithWind** [TheIllusiveC4/VeinMining#23]
my full config is here

{
	"enchantment": {
		// The rarity of the enchantment
		"rarity": "RARE",
		// The number of levels of the enchantment
		"levels": 1,
		// Whether or not to consider this enchantment as a treasure
		"isTreasure": false,
		// Whether or not this enchantment can be randomly selected for enchanting
		"isRandomlySelectable": true,
		// Whether or not this enchantment is available on books
		"isAvailableOnBooks": true,
		// The minimum enchanting power requirement for the first enchantment level
		"minPowerBase": 15,
		// The additional enchanting power requirement for each enchantment level after the first
		"minPowerPerLevel": 5,
		// List of enchantments that cannot be applied together with this enchantment
		"incompatibleEnchantments": []
	},
	"veinMining": {
		// The maximum number of blocks to mine without the enchantment
		"requireEffectiveTool": false,
		// The maximum number of blocks to mine without the enchantment
		"maxBlocksBase": 0,
		// The maximum distance from the source block without the enchantment
		"maxDistanceBase": 0,
		// The maximum number of blocks to mine per level of the enchantment
		"maxBlocksPerLevel": 50,
		// The maximum distance from the source block per level of the enchantment
		"maxDistancePerLevel": 15,
		// Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
		"diagonalMining": true,
		// Whether or not to move all drops to the same location
		"relocateDrops": true,
		// Whether or not the tool can break while mining additional blocks
		"preventToolDestruction": false,
		// Whether or not the tool takes damage from mining additional blocks
		"addToolDamage": true,
		// The multiplier to tool damage from mining additional blocks
		"toolDamageMultiplier": 1,
		// Whether or not the player gets exhaustion from mining additional blocks
		"addPlayerExhaustion": true,
		// The multiplier to player exhaustion from mining additional blocks
		"playerExhaustionMultiplier": 1.0,
		// Whether or not to stop vein mining when the tool can no longer be used
		"limitedByDurability": true,
		// Whether to activate vein mining by standing, crouching, or holding down the keybind
		"activationState": "KEYBIND",
		// List of whitelisted/blacklisted blocks or block tags
		"blocks": ["#c:ores" "minecraft:coal_ore", "minecraft:iron_ore", "minecraft:gold_ore", "minecraft:redstone_ore", "minecraft:emerald_ore", "minecraft:diamond_ore", "minecraft:ancient_debris"
],

		// Whether the blocks configuration is a whitelist or a blacklist
		"blocksPermission": "WHITELIST",
		// List of groupings by block IDs or block tags, comma-separated
		"groups": [
			"#c:topaz_ores",
			"#c:runite_ores",
			"#c:antimony_ores",
			"#c:sphalerite_ores",
			"#c:uranium_ores",
			"#c:sapphire_ores",
			"#c:nickel_ores",
			"#c:sheldonite_ores",
			"#c:vermiculite_ores",
			"#c:lutetium_ores",
			"#c:unobtainium_ores",
			"#c:lapis_ores",
			"#c:zinc_ores",
			"#c:platinum_ores",
			"#c:lunum_ores",
			"#c:tin_ores",
			"#c:stormyx_ores",
			"#c:adamantite_ores",
			"#c:lead_ores",
			"#c:aquarium_ores",
			"#c:copper_ores",
			"#c:aetherium_ores",
			"#c:asterite_ores",
			"#c:iron_ores",
			"#c:banglum_ores",
			"#c:certus_quartz_ores",
			"#c:cinnabar_ores",
			"#c:bauxite_ores",
			"#c:iridium_ores",
			"#c:sulfur_ores",
			"#c:quadrillum_ores",
			"#c:salt_ores",
			"#c:truesilver_ores",
			"#c:osmium_ores",
			"#c:diamond_ores",
			"#c:amethyst_ores",
			"#c:palladium_ores",
			"#c:tungsten_ores",
			"#c:aluminum_ores",
			"#c:prometheum_ores",
			"#c:sodalite_ores",
			"#c:emerald_ores",
			"#c:galaxium_ores",
			"#c:mythril_ores",
			"#c:carmot_ores",
			"#c:metite_ores",
			"#c:redstone_ores",
			"#c:cobalt_ores",
			"#c:tantalite_ores",
			"#c:peridot_ores",
			"#c:manganese_ores",
			"#c:silver_ores",
			"#c:titanium_ores",
			"#c:starrite_ores",
			"#c:orichalcum_ores",
			"#c:stellum_ores",
			"#c:ur_ores",
			"#c:coal_ores",
			"#c:kyber_ores",
			"#c:ruby_ores",
			"#c:pyrite_ores",
			"#c:gold_ores,#minecraft:gold_ores",
			"#c:galena_ores",
			"#c:quartz_ores"
		]
	}
}

after saving it and loading into the world it goes back to default config

**Comment by TheIllusiveC4** [comment]
Vein Mining version?

**Comment by OneWithWind** [comment]
0.0.9 1.17

**Comment by TheIllusiveC4** [comment]
Activation state should be `"KEYBINDING"`, not what you currently have.

If that doesn't fix it, send me your `latest.log` file.

**Comment by OneWithWind** [comment]
sorry for taking so long, but that fixed my issue thanks so much. its keeping my settings now that i corrected it to KEYBINDING. Thank you!!
