### ISSUE TITLE
Better Minecraft 1.16.5 versin

### ISSUE THREAD

**Issue by Kabrasaki** [TheIllusiveC4/VeinMining#24]
Vein miner has only worked once and it was when i broke a tree . After that no matter how much i tried and changed from standing to crounching to key binding it just won't work. I tried to go trough the command way but it tells me there are no commands, what should i do?

**Comment by TheIllusiveC4** [comment]
There are no commands in this mod.

Tell me your Vein Mining version and Forge/Fabric version (i.e. not just 1.16.5, I need the specific file version you're using).

In addition, show me your configuration file.

**Comment by yoksoman** [comment]
i got the same my vein miner is 1.16.5-012

**Comment by TheIllusiveC4** [comment]
Show me your configuration file and list out the steps to reproduce your issue.

**Comment by yoksoman** [comment]
do you have discord?

**Comment by yoksoman** [comment]
add me than we can talk yoksoman #2985

**Comment by TheIllusiveC4** [comment]
I have a Discord server you can join: https://discord.gg/JWgrdwt

However, I'd prefer if we discussed it here on GitHub for the sake of proper bug report archiving.

**Comment by SHXRKIEgg** [comment]
Creator of Better MC here, we have a mod that cuts whole trees down so this person is confused with your mod and doesn't actually know its an enchant you need and therefore why its not working on other things.

**Comment by TheIllusiveC4** [comment]
Alright then, thanks for the info. I'll close this issue then.
