### ISSUE TITLE
Can't add #forge:ores or it crashes my game.

### ISSUE THREAD

**Issue by imeangay** [TheIllusiveC4/VeinMining#27]
I can't add the exclusion to only mine ores with the mod or my game crashes, here's my config.

`
[enchantment]
	#Whether or not this enchantment can be applied on books
	canApplyOnBooks = true
	#The minimum enchantability requirement for the first enchantment level
	#Range: 1 ~ 100
	minEnchantabilityBase = 15
	#Whether or not to consider this enchantment as a treasure
	isTreasure = false
	#List of enchantments that cannot be applied together with this enchantment
	incompatibleEnchantments = []
	#Whether or not this enchantment can be offered by villagers for trade
	isVillagerTrade = true
	#Whether or not this enchantment can generate in loot
	isLootable = true
	#List of items that the enchantment can be applied on
	items = ["is:tool", "quark:pickarang", "quark:flamarang"]
	#The number of levels of the enchantment
	#Range: 1 ~ 5
	levels = 1
	#Whether or not this enchantment can be applied at the enchanting table
	canApplyAtEnchantingTable = true
	#The additional enchantability requirement for each enchantment level after the first
	#Range: 1 ~ 100
	minEnchantabilityPerLevel = 5
	#The rarity of the enchantment
	#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
	rarity = "RARE"

["vein mining"]
	#Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
	diagonalMining = true
	#Whether or not the tool can break while mining additional blocks
	preventToolDestruction = true
	#Whether the blocks configuration is a whitelist or a blacklist
	#Allowed Values: BLACKLIST, WHITELIST
	blocksPermission = "WHITELIST"
	#The maximum distance from the source block per level of the enchantment
	#Range: 1 ~ 100
	maxDistancePerLevel = 15
	#Whether or not to stop vein mining when the tool can no longer be used
	limitedByDurability = true
	#List of whitelisted/blacklisted blocks or block tags
	blocks = [#forge:ores]
	#The maximum number of blocks to mine without the enchantment
	#Range: 0 ~ 1000
	maxBlocksBase = 0
	#The multiplier to tool damage from mining additional blocks
	#Range: 0 ~ 1000
	toolDamageMultiplier = 1
	#Whether or not to move all drops to the same location
	relocateDrops = true
	#Whether or not the tool takes damage from mining additional blocks
	addToolDamage = true
	#The maximum distance from the source block without the enchantment
	#Range: 0 ~ 1000
	maxDistanceBase = 0
	#Whether or not to require an effective tool to vein mine blocks
	requireEffectiveTool = false
	#The multiplier to player exhaustion from mining additional blocks
	#Range: 0.0 ~ 1000.0
	playerExhaustionMultiplier = 1.0
	#The maximum number of blocks to mine per level of the enchantment
	#Range: 1 ~ 1000
	maxBlocksPerLevel = 50
	#Whether or not the player gets exhaustion from mining additional blocks
	addPlayerExhaustion = true

[groups]
	#List of groupings by block IDs or block tags, comma-separated
	groups = ["#forge:obsidian", "#forge:ores/coal", "#forge:ores/diamond", "#forge:ores/emerald", "#forge:ores/gold", "#forge:ores/iron", "#forge:ores/lapis", "#forge:ores/redstone", "#forge:ores/quartz", "#forge:ores/netherite_scrap", "#forge:ores/copper", "#forge:ores/tin", "#forge:ores/osmium", "#forge:ores/uranium", "#forge:ores/fluorite", "#forge:ores/lead", "#forge:ores/zinc", "#forge:ores/aluminum", "#forge:ores/nickel", "#forge:ores/silver", "#forge:ores/apatite", "#forge:ores/cinnabar", "#forge:ores/niter", "#forge:ores/ruby", "#forge:ores/sapphire", "#forge:ores/sulfur"]

`

here's my crash log
[crash-2021-08-03_03.01.22-server.txt](https://github.com/TheIllusiveC4/VeinMining/files/6923236/crash-2021-08-03_03.01.22-server.txt)

Not sure if it's something im doing wrong, or if it's a mod i have, but regardless, works fine without any exclusino, except i mine everything, and i only wanna mine ores.

Tried a new world, same thing occurs.

**Comment by TheIllusiveC4** [comment]
You don't have quotation marks around the entry. It should be `blocks = ["#forge:ores"]`.
