### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LeoraKnight** [TheIllusiveC4/VeinMining#34]
### Minecraft Version

1.17.1

### What happened?

How can I get this to work with deepslate and tuff ore? It doesnt seem to word with these with my current config. 

### How do you trigger this bug?

Config

[enchantment]
	#Whether or not this enchantment can be applied on books
	canApplyOnBooks = true
	#The minimum enchantability requirement for the first enchantment level
	#Range: 1 ~ 100
	minEnchantabilityBase = 15
	#Whether or not to consider this enchantment as a treasure
	isTreasure = true
	#List of enchantments that cannot be applied together with this enchantment
	incompatibleEnchantments = []
	#Whether or not this enchantment can be offered by villagers for trade
	isVillagerTrade = true
	#Whether or not this enchantment can generate in loot
	isLootable = true
	#List of items that the enchantment can be applied on
	items = ["is:tool", "quark:pickarang", "quark:flamarang"]
	#The number of levels of the enchantment
	#Range: 1 ~ 5
	levels = 1
	#Whether or not this enchantment can be applied at the enchanting table
	canApplyAtEnchantingTable = true
	#The additional enchantability requirement for each enchantment level after the first
	#Range: 1 ~ 100
	minEnchantabilityPerLevel = 5
	#The rarity of the enchantment
	#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
	rarity = "RARE"

["vein mining"]
	#Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
	diagonalMining = true
	#Whether or not the tool can break while mining additional blocks
	preventToolDestruction = true
	#Whether the blocks configuration is a whitelist or a blacklist
	#Allowed Values: BLACKLIST, WHITELIST
	blocksPermission = "WHITELIST"
	#The maximum distance from the source block per level of the enchantment
	#Range: 1 ~ 100
	maxDistancePerLevel = 20
	#Whether or not to stop vein mining when the tool can no longer be used
	limitedByDurability = true
	#List of whitelisted/blacklisted blocks or block tags
	blocks = ["#forge:ores", "#minecraft:logs"]
	#The maximum number of blocks to mine without the enchantment
	#Range: 0 ~ 1000
	maxBlocksBase = 15
	#The multiplier to tool damage from mining additional blocks
	#Range: 0 ~ 1000
	toolDamageMultiplier = 0
	#Whether or not to move all drops to the same location
	relocateDrops = true
	#Whether or not the tool takes damage from mining additional blocks
	addToolDamage = true
	#The maximum distance from the source block without the enchantment
	#Range: 0 ~ 1000
	maxDistanceBase = 15
	#Whether or not to require an effective tool to vein mine blocks
	requireEffectiveTool = true
	#The multiplier to player exhaustion from mining additional blocks
	#Range: 0.0 ~ 1000.0
	playerExhaustionMultiplier = 1.0
	#The maximum number of blocks to mine per level of the enchantment
	#Range: 1 ~ 1000
	maxBlocksPerLevel = 50
	#Whether or not the player gets exhaustion from mining additional blocks
	addPlayerExhaustion = true

[groups]
	#List of groupings by block IDs or block tags, comma-separated
	groups = ["#forge:obsidian", "#forge:ores/coal", "#forge:ores/diamond", "#forge:ores/emerald", "#forge:ores/gold", "#forge:ores/iron", "#forge:ores/lapis", "#forge:ores/redstone", "#forge:ores/quartz", "#forge:ores/netherite_scrap", "#forge:ores/copper", "#forge:ores/tin", "#forge:ores/osmium", "#forge:ores/uranium", "#forge:ores/fluorite", "#forge:ores/lead", "#forge:ores/zinc", "#forge:ores/aluminum", "#forge:ores/nickel", "#forge:ores/silver", "#forge:ores/apatite", "#forge:ores/cinnabar", "#forge:ores/niter", "#forge:ores/ruby", "#forge:ores/sapphire", "#forge:ores/sulfur"]

### Loader

Forge

### Loader Version

Latest

### Mod Version

Latest

**Comment by TheIllusiveC4** [comment]
```
blocks = ["#forge:ores", "#minecraft:logs"]
```

Most likely the ores are not tagged under these categories. You'll have to either add the ore names directly or add them to the `#forge:ores` tag.
