### ISSUE TITLE
[Bug]: Game Crashes While Loading A World

### ISSUE THREAD

**Issue by bowsmin12** [TheIllusiveC4/VeinMining#35]
### Minecraft Version

1.17.1

### What happened?

I have a small to medium sized fabric modpack going. So I am unsure if it's conflicting with another mod or if it's vein miner it's self. When I install the mod everything works properly until the world loads 100% then it comes up with this crash message: The game crashed whilst exception in server tick loop
Error: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
Exit Code: -1
I can't find any other vein mining mods for 1.17 fabric so I kinda hope we can fix this.

### How do you trigger this bug?

1.Install Vein miner
2.Load world?
3.I'm not really sure what to put in this box
...

### Loader

Fabric

### Loader Version

Essential 1.17.1 with fabric API, and other tools for other mods

### Mod Version

veinmining-fabric-0.0.11-1.17.1.jar

### Relevant Log Outputs

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 11/28/21, 1:11 PM
Description: Exception in server tick loop

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:711)
	at top.theillusivec4.veinmining.veinmining.logic.BlockGroups.createGroup(BlockGroups.java:59)
	at top.theillusivec4.veinmining.veinmining.logic.BlockGroups.init(BlockGroups.java:40)
	at top.theillusivec4.veinmining.veinmining.logic.BlockProcessor.rebuild(BlockProcessor.java:44)
	at top.theillusivec4.veinmining.VeinMiningMod.lambda$onInitialize$0(VeinMiningMod.java:57)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:48)
	at net.minecraft.server.MinecraftServer.handler$bae000$afterSetupServer(MinecraftServer.java:4307)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 602332368 bytes (574 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5751
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 47254.64
	Virtual memory used (MB): 40976.25
	Swap memory total (MB): 14544.48
	Swap memory used (MB): 3101.66
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adapaxels: AdaPaxels 1.2.2+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancedcompass: Advanced Compass 1.2.6
		appleskin: AppleSkin mc1.17.1-2.2.0
		architectury: Architectury 2.6.35
		autopath: Automatic Path 1.4.6
		awesomedungeon: Awesome Dungeon 1.1.2
		balm-fabric: Balm 1.8.0+0
		boatcontainer: BoatContainer 1.0.3
		bountiful: Bountiful 1.0.0
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		carrier: Carrier 1.8.2
		charm: Charm 3.3.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v5 5.1.40
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.7-1.17.1
		dimores: DimensionalOres 1.0.1
		eatinganimationid: Eating Animation 1.2
		essential: Essential 1577+release-launch-1.17
		essential-container: essential-container 1.0.0
		essential-loader: essential-loader 1.0.0
		expandedstorage: Expanded Storage 7.3.0
		fabric: Fabric API 0.43.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.2+cf39a74318
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+cf39a74318
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+cf39a74318
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.3+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+cf39a74318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.6+2a2bb57318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.4+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.6+cf39a74318
		fabric-models-v0: Fabric Models (v0) 0.3.1+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.12+cf39a74318
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.6+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+cf39a74318
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+cf39a74318
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+cf39a74318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+cf39a74318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+cf39a74318
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+377137cc18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+cf39a74318
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.15+cf39a74318
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.2+cf39a74318
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.2+cf39a74318
		fabricloader: Fabric Loader 0.12.5
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		geckolib3: Geckolib 3.0.29
		greater_eye: Greater Eye of Ender 1.2.11
		hookshot: Hookshot 22.0
		hwg: Happiness is a Warm Gun 1.0.27
		illuminations: Illuminations 1.10
		inmis: Inmis 2.3.2-1.17.1
		interactic: Interactic 0.1.6-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		just_end_anchor: Just An End Anchor 1.0.1
		kambrik: Kambrik 1.1.0
		letsleepingdogslie: Let Sleeping Dogs Lie - Fabric (Unofficial) 1.0.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		magic_mirror: Magic Mirror 1.3.2
		mcdar: MC Dungeons Artifacts 1.4.2
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		mocolors: Mo' Colors 1.2.2
		modmenu: Mod Menu 2.0.14
		morebannerfeatures: More Banner Features 1.1.1
		moreboots: More Boots 1.1.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.5
		notforgotten: Not Forgotten 1.0.0
		omega-config: OmegaConfig 1.0.8
		optifabric: OptiFabric 1.12.5
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		oystersreborn: Oysters Reborn 1.0.0
		playerabilitylib: Pal 1.3.0
		reborncore: Reborn Core 5.0.11-beta
		repurposed_structures: Repurposed Structures 2.5.7+1.17.1
		roughlyenoughitems: Roughly Enough Items 6.2.335
		scorch: Scorch 1.2.0
		secondchance: Second Chance 1.2.0
		somnus: Somnus API 0.0.13-1.17.1
		spirit: Spirit 1.1.0
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.11-beta
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transportables: Transportables 1.0.6
		trinkets: Trinkets 3.0.4
		veinmining: Vein Mining 0.0.11-1.17.1
		waystones: Waystones 8.2.0+0
		winged: Winged Mod 1.17.1-3.0.0
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.17.1_HD_U_H1
	OptiFine Build: 20211104-012451
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 457.51
	OpenGlRenderer: GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_H1
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/bowsm/AppData/Roaming/.minecraft/essential_1.17.1/.optifine/OptiFine_1.17.1_HD_U_H1/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by TheIllusiveC4** [comment]
It looks like something went wrong with your config file. Did you edit it in any way? Can you share your config file?

**Comment by bowsmin12** [comment]
Honestly don't know how to get to the config file. I have the Mod menu mod I think that allows you to change settings there otherwise I don't know how to change them anywhere else.

**Comment by TheIllusiveC4** [comment]
It's in the `config` folder of your Minecraft instance, `veinmining.json5`.

**Comment by bowsmin12** [comment]
I've found the file and opened it with notepad. I don't know what I'm looking for though, so I'll copy paste. Sorry if this isn't helpful.
{
	"enchantment": {
		// The rarity of the enchantment ("COMMON", "UNCOMMON", "RARE", "VERY_RARE")
		"rarity": "RARE",
		// The number of levels of the enchantment
		"levels": 1,
		// Whether or not to consider this enchantment as a treasure
		"isTreasure": false,
		// Whether or not this enchantment can be randomly selected for enchanting
		"isRandomlySelectable": true,
		// Whether or not this enchantment is available on books
		"isAvailableOnBooks": true,
		// The minimum enchanting power requirement for the first enchantment level
		"minPowerBase": 15,
		// The additional enchanting power requirement for each enchantment level after the first
		"minPowerPerLevel": 5,
		// List of enchantments that cannot be applied together with this enchantment
		"incompatibleEnchantments": []
	},
	"veinMining": {
		// The maximum number of blocks to mine without the enchantment
		"requireEffectiveTool": false,
		// The maximum number of blocks to mine without the enchantment
		"maxBlocksBase": 25,
		// The maximum distance from the source block without the enchantment
		"maxDistanceBase": 51,
		// The maximum number of blocks to mine per level of the enchantment
		"maxBlocksPerLevel": 50,
		// The maximum distance from the source block per level of the enchantment
		"maxDistancePerLevel": 15,
		// Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
		"diagonalMining": true,
		// Whether or not to move all drops to the same location
		"relocateDrops": true,
		// Whether or not the tool can break while mining additional blocks
		"preventToolDestruction": true,
		// Whether or not the tool takes damage from mining additional blocks
		"addToolDamage": true,
		// The multiplier to tool damage from mining additional blocks
		"toolDamageMultiplier": 1,
		// Whether or not the player gets exhaustion from mining additional blocks
		"addPlayerExhaustion": true,
		// The multiplier to player exhaustion from mining additional blocks
		"playerExhaustionMultiplier": 1.0,
		// Whether or not to stop vein mining when the tool can no longer be used
		"limitedByDurability": true,
		// Whether to activate vein mining by standing, crouching, or holding down the keybind ("STANDING", "CROUCHING", "KEYBINDING")
		"activationState": "STANDING",
		// List of whitelisted/blacklisted blocks or block tags
		"blocks": [],
		// Whether the blocks configuration is a whitelist or a blacklist ("WHITELIST", "BLACKLIST")
		"blocksPermission": "BLACKLIST",
		// List of groupings by block IDs or block tags, comma-separated
		"groups": [
			""
		]
	}
}

**Comment by TheIllusiveC4** [comment]
You have an empty value in your `"groups"` for some reason. This should be filling out by default. Did you change this value at some point?

**Comment by bowsmin12** [comment]
I think I pressed the reset button in the Mod menu. The issue was still happening before doing that because I did this in response to the crashes. I attempted to put stone on the blacklist and thought that might have been part of the reason for the crashes for whatever reason. So I think I ended up pressing both resets one way or another.

**Comment by TheIllusiveC4** [comment]
Alright, try deleting the config file and then loading the game up again so it generates a new one. Don't change anything in the config file before reporting back.

**Comment by bowsmin12** [comment]
Well I deleted the json file and had to reinstall the mod. (I deleted it to play the rest of the pack while figuring this out) Everything seems to work now even with the few changes I've made to the config after. While I have your attention if you could help me a little more.(whenever you have time) I'm confused on what I should put for the blacklist. Lets say I wanted to put stone on the blacklist. can I get a little walkthrough to work it properly?

**Comment by TheIllusiveC4** [comment]
Like this:
```json
"blocks": ["minecraft:stone"]
```
