### ISSUE TITLE
[Bug]: Return of Issue #36, The Infinite Loop

### ISSUE THREAD

**Issue by ZilverLazarus** [TheIllusiveC4/VeinMining#38]
### Minecraft Version

1.16.5

### What happened?

Upon loading into an existing or new world, the game crashes and gives the crash reason of "Exception in server tick loop". 

From my understanding, Vein Mining 1.16.5-0.15 fixed #36 (as listed in the changelog on the CurseForge page), so perhaps something was overlooked?

### How do you trigger this bug?

1. Load the game with Dungeons Libraries (dungeons_libraries-1.16.5-0.0.3-beta) and Vein Mining (veinmining-forge-1.16.5-0.15) installed.
2. Upon game loading into the main menu, try to access any newly created or already existing world.
3. Wait for some time while loading in the world.
4. Joining world... 
5. And the game crashes.

To confirm the issue further, loading the world with either of these two mods disabled seems to fix the issue.

### Loader

Forge

### Loader Version

Forge 36.2.20

### Mod Version

veinmining-forge-1.16.5-0.15

### Relevant Log Outputs

Crash Report:
https://pastebin.com/UDnQ63gB

Latest:
(Too big for pastebin free users such as me. Let me know if you still want the log by some other means.)

**Comment by TheIllusiveC4** [comment]
Ohhh no, that's a problem.

I did fix the issue between Vein Mining and Dungeon Libraries specifically, but it seems like the issue is coming from Immersive Engineering this time. Not that it's solely their fault, it's just that they're doing something that doesn't play nicely with these other two mods involved and I should probably have accounted for that. I'll need to figure something else out for this issue.

**Comment by ZilverLazarus** [comment]
> Ohhh no, that's a problem.
> 
> I did fix the issue between Vein Mining and Dungeon Libraries specifically, but it seems like the issue is coming from Immersive Engineering this time. Not that it's solely their fault, it's just that they're doing something that doesn't play nicely with these other two mods involved and I should probably have accounted for that. I'll need to figure something else out for this issue.

Sounds good. Thanks for the quick response and good luck.
