### ISSUE TITLE
[Bug]: No config what so ever????

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/VeinMining#39]
### Minecraft Version

1.18.1

### What happened?

I am very confused. I even checked the wiki on how to config this fabric mod... There is literally no configs for this anywhere. I have cloth for fabric & when i go to C:\Users\deann\AppData\Roaming\.minecraft\config There is no veinminer config file. I even tried searching the file through the search bar with no avail.... And this bug says its for 1.17.1 but i reporting this for the 1.18 version of this mod.

### How do you trigger this bug?

1.NA
2.NA
3.NA
...NA

### Loader

Fabric

### Loader Version

fabric-loader-0.12.12-1.18.1

### Mod Version

Current Mod Build

**Comment by TheIllusiveC4** [comment]
And you're sure you have Cloth Config installed? This mod: https://www.curseforge.com/minecraft/mc-mods/cloth-config

And that you've loaded up the game at least once with it installed?

**Comment by JayDo96** [comment]
The config should be in your world's folder if its the same as the forge config
