### ISSUE TITLE
[Bug]: Command doesn't exists

### ISSUE THREAD

**Issue by luizfx22** [TheIllusiveC4/VeinMining#40]
### Minecraft Version

1.16.5

### What happened?

The command to quickly add more tools and blocks to whitelist doesn't appear on client nor server.

### How do you trigger this bug?

There's no trigger, just installed in a new fresh version and nothing works. (Changed the keybinding though)

### Loader

Forge

### Loader Version

36,2,22

### Mod Version

1,16,5-0,15

**Comment by TheIllusiveC4** [comment]
This mod doesn't have any native commands. Are you confusing this with another mod?

**Comment by luizfx22** [comment]
Probably 😅... 
I'm used to VeinMiner, wich doesn't support 1.16.5. Oh, btw I'm having some issues with adding the Chisel blocks into whitelist, blocks like marble (raw), limestone (raw) and basalt (raw). Do you know how to do this?

**Comment by TheIllusiveC4** [comment]
You would just add those block ids into the blocks list in the config file.

For more info, here is the wiki page on configuration:
https://github.com/TheIllusiveC4/VeinMining/wiki/Configuration
