### ISSUE TITLE
[Bug]: Despite config, enchant does not go above II

### ISSUE THREAD

**Issue by CritFlaw** [TheIllusiveC4/VeinMining#44]
### Minecraft Version

1.18.1

### What happened?

When trying to combine 2 vein mining II books, the result is still vein mining II. The config is below:
https://mcpaste.io/a439147c56082a30

### How do you trigger this bug?

1. Get several vein mining 1 books from villager
2. Try combining in an anvil
3. Potentially include this modpack https://drive.google.com/file/d/16kHRbRV1mLADMg1iC04upuTRHJrKhtFz/view?usp=sharing

### Loader

Forge

### Loader Version

39.0.59

### Mod Version

0.16

### Relevant Log Outputs

The log is too large to paste due to a `[Server thread/WARN]: Skipping Entity with id ` being spammed in chat over and over but I can provide if need be.

**Comment by JayDo96** [comment]
I am having the same issue on my private server running forge 1.18

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this bug with Vein Mining by itself, but I can reproduce it with the listed modpack. This suggests that this is a mod conflict. You will have to isolate the mod conflict before I can investigate further.

Edit: I suggest starting by removing any mods that affect enchantments in any way.

**Comment by JayDo96** [comment]
After doing further testing I have determined it is the apotheosis mod. In it's config it restricts enchantments so make sure you change the max level in apotheosis as well.

**Comment by TheIllusiveC4** [comment]
Okay, thank you very much for figuring that out. I'll officially conclude that this is just an Apotheosis feature that people should be aware of changing as well.

**Comment by CritFlaw** [comment]
@JayDo96 Thank you very much for going through that. I thought it might've been Apotheosis but didn't get a chance to verify.
