### ISSUE TITLE
[Bug]: activate button is used as deactivate button

### ISSUE THREAD

**Issue by TypzVR** [TheIllusiveC4/VeinMining#45]
### Minecraft Version

1.18.1

### What happened?

When mining a terrain with the pickaxe with Vein Mining on it, it will always be vein mined. To not have this, I need to use the activate button to not veinmine a whole terrain. This is very annoying because this can mess up my world/base/progress and more. I use this on a server, if that helps with anything.

### How do you trigger this bug?

1. Mine with the tool with vine meiner without holding the activate button
2. 
3.
...

### Loader

Fabric

### Loader Version

Fabric 0.13.1

### Mod Version

0.0.11-1.18

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, setting up the keybindings and everything, the activate button works as it's supposed to (as in, vein mining does not work unless the activate button is held down).

Can you share your config settings? Did you make sure the configs are set correctly on your _client_ also? What are you using as your activation key bind?

**Comment by SarahLouise1978** [comment]
Hello, I'm having the same problem as this, where vein mining is activated as default and the keybind just mines 1 block. I have tried to adjust it in the config files, but it has made no difference! I have used different latters as the keybind. I am using forge 39.0.66 and veinmining 1.18.1-0.16jar.
Thanks

**Comment by TheIllusiveC4** [comment]
Okay, what did you adjust exactly in the configuration file? Please show the current settings of your `veinmining-client.toml` file. The `activationState` field should be set to `"KEYBINDING"`.

**Comment by SarahLouise1978** [comment]
Hello, thanks for getting back to me, hope this is helpful





Sent from Yahoo Mail on Android 
 
  On Thu, 10 Feb 2022 at 11:25, ***@***.***> wrote:   


Okay, what did you adjust exactly in the configuration file? Please show the current settings of your veinmining-client.toml file. The activationState field should be set to "KEYBINDING".

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TheIllusiveC4** [comment]
If something was supposed to be attached to your email, then I don't see anything. Please try again on GitHub directly.

**Comment by SarahLouise1978** [comment]
![16444979480147544992789205043846](https://user-images.githubusercontent.com/57772073/153413211-28822d92-f7c3-440a-b47d-bd31c55e5529.jpg)

I hope that worked!

**Comment by TheIllusiveC4** [comment]
Hm, okay, that config looks right then. So if you save the file, then start your game and load up your world, the keybinding does not do anything? Vein Mining still activates by default without pressing anything?

**Comment by SarahLouise1978** [comment]
yes thats right!

**Comment by TheIllusiveC4** [comment]
Hm, unfortunately I cannot reproduce it. Setting the configs in my testing instance to the same as above, the keybinding works correctly. Are you sure you're saving the configuration file and that it's located in the right folder?
