### ISSUE TITLE
[BUG]: Whitelist not working

### ISSUE THREAD

**Issue by xJasper222** [TheIllusiveC4/VeinMining#47]
### Minecraft Version

1.18.1

### What happened?

I configured the items, added some ores from other mods and it worked but when i wanted to add whitelist so it doesnt destroy everything its not working at all, maybe i did a mistake i dont know help!

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

FABRIC API  0.13.1- 1.18.1

### Mod Version

veinmining-fabric-0.0.11-1.18.jar

### Relevant Log Outputs

{
	"enchantment": {
		// The rarity of the enchantment ("COMMON", "UNCOMMON", "RARE", "VERY_RARE")
		"rarity": "COMMON",
		// The number of levels of the enchantment
		"levels": 1,
		// Whether or not to consider this enchantment as a treasure
		"isTreasure": false,
		// Whether or not this enchantment can be randomly selected for enchanting
		"isRandomlySelectable": true,
		// Whether or not this enchantment is available on books
		"isAvailableOnBooks": true,
		// The minimum enchanting power requirement for the first enchantment level
		"minPowerBase": 1,
		// The additional enchanting power requirement for each enchantment level after the first
		"minPowerPerLevel": 1,
		// List of enchantments that cannot be applied together with this enchantment
		"incompatibleEnchantments": []
	},
	"veinMining": {
		// The maximum number of blocks to mine without the enchantment
		"requireEffectiveTool": true,
		// The maximum number of blocks to mine without the enchantment
		"maxBlocksBase": 25,
		// The maximum distance from the source block without the enchantment
		"maxDistanceBase": 25,
		// The maximum number of blocks to mine per level of the enchantment
		"maxBlocksPerLevel": 70,
		// The maximum distance from the source block per level of the enchantment
		"maxDistancePerLevel": 70,
		// Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
		"diagonalMining": true,
		// Whether or not to move all drops to the same location
		"relocateDrops": true,
		// Whether or not the tool can break while mining additional blocks
		"preventToolDestruction": false,
		// Whether or not the tool takes damage from mining additional blocks
		"addToolDamage": false,
		// The multiplier to tool damage from mining additional blocks
		"toolDamageMultiplier": 1,
		// Whether or not the player gets exhaustion from mining additional blocks
		"addPlayerExhaustion": false,
		// The multiplier to player exhaustion from mining additional blocks
		"playerExhaustionMultiplier": 1.0,
		// Whether or not to stop vein mining when the tool can no longer be used
		"limitedByDurability": true,
		// Whether to activate vein mining by standing, crouching, or holding down the keybind ("STANDING", "CROUCHING", "KEYBINDING")
		"activationState": "CROUCHING",
		// List of whitelisted/blacklisted blocks or block tags
		"blocks": [
			"#c:topaz_ores",
			"#c:valley:saltpeter_ore",
			"#c:runite_ores",
			"#c:antimony_ores",
			"#c:betterend:ender_ore",
			"#c:sphalerite_ores",
			"#c:uranium_ores",
			"#c:sapphire_ores",
			"#c:valley:nether_coal_ore",
			"#c:nickel_ores",
			"#c:sheldonite_ores",
			"#c:vermiculite_ores",
			"#c:lutetium_ores",
			"#c:unobtainium_ores",
			"#c:lapis_ores",
			"#c:zinc_ores",
			"#c:platinum_ores",
			"#c:lunum_ores",
			"#c:tin_ores",
			"#c:stormyx_ores",
			"#c:adamantite_ores",
			"#c:lead_ores",
			"#c:aquarium_ores",
			"#c:copper_ores",
			"#c:valley:deepslate_saltpeter_ore",
			"#c:valley:salt_ore",
			"#c:aetherium_ores",
			"#c:betterend:thallasium_ore",
			"#c:asterite_ores",
			"#c:iron_ores",
			"#c:banglum_ores",
			"#c:certus_quartz_ores",
			"#c:cinnabar_ores",
			"#c:bauxite_ores",
			"#c:iridium_ores",
			"#c:valley:pslate_mixed_ore",
			"#c:sulfur_ores",
			"#c:quadrillum_ores",
			"#c:salt_ores",
			"#c:truesilver_ores",
			"#c:osmium_ores",
			"#c:diamond_ores",
			"#c:amethyst_ores",
			"#c:palladium_ores",
			"#c:tungsten_ores",
			"#c:valley:jungle_sporey",
			"#c:aluminum_ores",
			"#c:prometheum_ores",
			"#c:sodalite_ores",
			"#c:emerald_ores",
			"#c:galaxium_ores",
			"#c:mythril_ores",
			"#c:carmot_ores",
			"#c:metite_ores",
			"#c:redstone_ores",
			"#c:cobalt_ores",
			"#c:tantalite_ores",
			"#c:betternether:nether_lapis_ore",
			"#c:betterend:amber_ore",
			"#c:peridot_ores",
			"#c:valley:nether_salt",
			"#c:manganese_ores",
			"#c:silver_ores",
			"#c:titanium_ores",
			"#c:starrite_ores",
			"#c:orichalcum_ores",
			"#c:stellum_ores",
			"#c:ur_ores",
			"#c:valley:mixed_ore",
			"#c:coal_ores",
			"#c:kyber_ores",
			"#c:ruby_ores",
			"#c:betternether:nether_redstone_ore",
			"#c:pyrite_ores",
			"#c:betternether:cincinnasite_ore",
			"#c:betternether:nether_ruby_ore",
			"#c:gold_ores,#minecraft:gold_ores",
			"#c:galena_ores",
			"#c:quartz_ores"
		],
		// Whether the blocks configuration is a whitelist or a blacklist ("WHITELIST", "BLACKLIST")
		"blocksPermission": "WHITELIST",
		// List of groupings by block IDs or block tags, comma-separated
		"groups": [
			"#c:topaz_ores",
			"#c:valley:saltpeter_ore",
			"#c:runite_ores",
			"#c:antimony_ores",
			"#c:betterend:ender_ore",
			"#c:sphalerite_ores",
			"#c:uranium_ores",
			"#c:sapphire_ores",
			"#c:valley:nether_coal_ore",
			"#c:nickel_ores",
			"#c:sheldonite_ores",
			"#c:vermiculite_ores",
			"#c:lutetium_ores",
			"#c:unobtainium_ores",
			"#c:lapis_ores",
			"#c:zinc_ores",
			"#c:platinum_ores",
			"#c:lunum_ores",
			"#c:tin_ores",
			"#c:stormyx_ores",
			"#c:adamantite_ores",
			"#c:lead_ores",
			"#c:aquarium_ores",
			"#c:copper_ores",
			"#c:valley:deepslate_saltpeter_ore",
			"#c:valley:salt_ore",
			"#c:aetherium_ores",
			"#c:betterend:thallasium_ore",
			"#c:asterite_ores",
			"#c:iron_ores",
			"#c:banglum_ores",
			"#c:certus_quartz_ores",
			"#c:cinnabar_ores",
			"#c:bauxite_ores",
			"#c:iridium_ores",
			"#c:valley:pslate_mixed_ore",
			"#c:sulfur_ores",
			"#c:quadrillum_ores",
			"#c:salt_ores",
			"#c:truesilver_ores",
			"#c:osmium_ores",
			"#c:diamond_ores",
			"#c:amethyst_ores",
			"#c:palladium_ores",
			"#c:tungsten_ores",
			"#c:valley:jungle_sporey",
			"#c:aluminum_ores",
			"#c:prometheum_ores",
			"#c:sodalite_ores",
			"#c:emerald_ores",
			"#c:galaxium_ores",
			"#c:mythril_ores",
			"#c:carmot_ores",
			"#c:metite_ores",
			"#c:redstone_ores",
			"#c:cobalt_ores",
			"#c:tantalite_ores",
			"#c:betternether:nether_lapis_ore",
			"#c:betterend:amber_ore",
			"#c:peridot_ores",
			"#c:valley:nether_salt",
			"#c:manganese_ores",
			"#c:silver_ores",
			"#c:titanium_ores",
			"#c:starrite_ores",
			"#c:orichalcum_ores",
			"#c:stellum_ores",
			"#c:ur_ores",
			"#c:valley:mixed_ore",
			"#c:coal_ores",
			"#c:kyber_ores",
			"#c:ruby_ores",
			"#c:betternether:nether_redstone_ore",
			"#c:pyrite_ores",
			"#c:betternether:cincinnasite_ore",
			"#c:betternether:nether_ruby_ore",
			"#c:gold_ores,#minecraft:gold_ores",
			"#c:galena_ores",
			"#c:quartz_ores"
		]
	}
}

**Comment by KMFrench1** [comment]
Set you configs to this. It is how I have it set up and it works fine.

"activationState": "CROUCHING",
		// List of whitelisted/blacklisted blocks or block tags
		"blocks": [
			"#c:ores"
		],
		// Whether the blocks configuration is a whitelist or a blacklist ("WHITELIST", "BLACKLIST")
		"blocksPermission": "WHITELIST",

**Comment by TheIllusiveC4** [comment]
You should change your config to the one in the comment above, as stated in the wiki as well.

Your issue is that in `"blocks"` you have:
```
"#c:gold_ores,#minecraft:gold_ores",
```

This is an invalid entry, and probably causing the entire configuration to fail and reset. You cannot copy the entries from `"groups"` into `"blocks"`, they have different formats.

**Comment by xJasper222** [comment]
When i changed it to it only detects vanilla ores

> // List of whitelisted/blacklisted blocks or block tags
> "blocks": [
> "#c:ores"
> ],
> // Whether the blocks configuration is a whitelist or a blacklist ("WHITELIST", "BLACKLIST")
> "blocksPermission": "WHITELIST",

**Comment by TheIllusiveC4** [comment]
It only detects ores that are properly tagged in `c:ores`. Which is vanilla ores, but modded ores may or may not do that. You will need to either add those ores in manually, or make your own datapack that tags the ores properly.
