### ISSUE TITLE
[Feature]: Support for ConfigGUI added by forge

### ISSUE THREAD

**Issue by SeanOMik** [TheIllusiveC4/VeinMining#48]
### What is the new feature or improvement?

There should be an option to modify the client's config through the ConfigGUI that was added by forge. It's annoying to have to shut down your game, find and edit the config file, and then start your game back up.

I don't think it would be a difficult thing to implement, but idk the inner workings of this mod, so it might be lol

**Comment by TheIllusiveC4** [comment]
Yeah, I'll definitely look into this once I have the time.
