### ISSUE TITLE
[Bug]: Enchanting table not applying the enchants on 1.18

### ISSUE THREAD

**Issue by SheroxGG** [TheIllusiveC4/VeinMining#49]
### Minecraft Version

1.18.1

### What happened?

I have configured the Mod so it has 5 enchantments levels, and each enchantment lvl increase the mined blocks by 2. Thats working fine, but for some reason I cant manage to get the enchantment via Enchanting table. 

[enchantment]
	#The rarity of the enchantment
	#Allowed Values: COMMON, UNCOMMON, RARE, VERY_RARE
	rarity = "RARE"
	#The number of levels of the enchantment
	#Range: 1 ~ 5
	levels = 5
	#Whether or not to consider this enchantment as a treasure
	isTreasure = true
	#Whether or not this enchantment can be offered by villagers for trade
	isVillagerTrade = true
	#Whether or not this enchantment can generate in loot
	isLootable = true
	#Whether or not this enchantment can be applied at the enchanting table
	canApplyAtEnchantingTable = true
	#Whether or not this enchantment can be applied on books
	canApplyOnBooks = true
	#The minimum enchantability requirement for the first enchantment level
	#Range: 1 ~ 100
	minEnchantabilityBase = 1
	#The additional enchantability requirement for each enchantment level after the first
	#Range: 1 ~ 100
	minEnchantabilityPerLevel = 5
	#List of enchantments that cannot be applied together with this enchantment
	incompatibleEnchantments = []
	#List of items that the enchantment can be applied on
	items = ["is:tool", "quark:pickarang", "quark:flamerang"]

["vein mining"]
	#Whether or not to require an effective tool to vein mine blocks
	requireEffectiveTool = false
	#The maximum number of blocks to mine without the enchantment
	#Range: 0 ~ 1000
	maxBlocksBase = 0
	#The maximum distance from the source block without the enchantment
	#Range: 0 ~ 1000
	maxDistanceBase = 0
	#The maximum number of blocks to mine per level of the enchantment
	#Range: 1 ~ 1000
	maxBlocksPerLevel = 2
	#The maximum distance from the source block per level of the enchantment
	#Range: 1 ~ 100
	maxDistancePerLevel = 2
	#Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
	diagonalMining = false
	#Whether or not to stop vein mining when the tool can no longer be used
	limitedByDurability = true
	#Whether or not to move all drops to the same location
	relocateDrops = true
	#Whether or not the tool can break while mining additional blocks
	preventToolDestruction = true
	#Whether or not the tool takes damage from mining additional blocks
	addToolDamage = true
	#The multiplier to tool damage from mining additional blocks
	#Range: 0 ~ 1000
	toolDamageMultiplier = 1
	#Whether or not the player gets exhaustion from mining additional blocks
	addPlayerExhaustion = true
	#The multiplier to player exhaustion from mining additional blocks
	#Range: 0.0 ~ 1000.0
	playerExhaustionMultiplier = 1.0
	#List of whitelisted/blacklisted blocks or block tags
	blocks = []
	#Whether the blocks configuration is a whitelist or a blacklist
	#Allowed Values: BLACKLIST, WHITELIST
	blocksPermission = "BLACKLIST"

[groups]
	#List of groupings by block IDs or block tags, comma-separated
	groups = ["#forge:obsidian", "#forge:ores/coal", "#forge:ores/diamond", "#forge:ores/emerald", "#forge:ores/gold", "#forge:ores/iron", "#forge:ores/lapis", "#forge:ores/redstone", "#forge:ores/quartz", "#forge:ores/netherite_scrap", "#forge:ores/copper", "#forge:ores/tin", "#forge:ores/osmium", "#forge:ores/uranium", "#forge:ores/fluorite", "#forge:ores/lead", "#forge:ores/zinc", "#forge:ores/aluminum", "#forge:ores/nickel", "#forge:ores/silver", "#forge:ores/apatite", "#forge:ores/cinnabar", "#forge:ores/niter", "#forge:ores/ruby", "#forge:ores/sapphire", "#forge:ores/sulfur"]

### How do you trigger this bug?

1. Make sure you have canApplyAtEnchantingTable = true
2. Create an enchanting table, try to enchant it with lapiz

### Loader

Forge

### Loader Version

39.0.85

### Mod Version

1.18.1-0.17

**Comment by TheIllusiveC4** [comment]
```
#Whether or not to consider this enchantment as a treasure
isTreasure = true
```

Setting this property to `true` makes it unavailable from the enchanting table. As an example, Mending is also considered a treasure enchantment.

**Comment by SheroxGG** [comment]
Got it! Thanks a lot! I thought that option would make it appear on chest aswell!

**Comment by TheIllusiveC4** [comment]
That would be the `isLootable` option, which you have as `true` already so it should work as-is for chest loot.
