### ISSUE TITLE
possibly enchantless - suggestion

### ISSUE THREAD

**Issue by superon** [TheIllusiveC4/VeinMining#5]
wondering if you'd consider adding the option to have this work without the need for the enchant to be added to a tool

**Comment by TheIllusiveC4** [comment]
While this isn't strictly in the spirit of the mod, and there are other vein mining alternatives that may fit your preferences more closely, it's already possible to accomplish this. The `maxBlocksBase` and `maxDistanceBase` config options govern how much vein mining a player can achieve without the enchantment. If you wish to disable the enchantment entirely, you can also do this through the enchantment configuration options.

**Comment by superon** [comment]
ahhh yes, fantastic, i had actually already tried this but just didn't realised it'd need a restart :) other option don't behave quite the same way so this suits my purposes very well thankyou
