### ISSUE TITLE
[Bug]: Auto Active

### ISSUE THREAD

**Issue by Vilkx** [TheIllusiveC4/VeinMining#50]
### Minecraft Version

1.16.5

### What happened?

Veinminer is always active and will destroy everything. i went into the config of my server but i have no option to change the activation method there is no line even showing a activation method in the config. My server is using the better minecraft modpack

### How do you trigger this bug?

1.Mining
2.
3.
...

### Loader

Forge

### Loader Version

Forge 36.2.29

### Mod Version

Vein Miner !.16.5

**Comment by TheIllusiveC4** [comment]
As described here on the [wiki page](https://github.com/TheIllusiveC4/VeinMining/wiki/Configuration#configuring-activation-method), the activation method is in the client-side config located in your client's config folder. The file is called `veinmining-client.toml`, and you can change the activation method there. Also, to be clear, the vein mining behavior by default can be turned off while you crouch.
