### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MinnieMagma** [TheIllusiveC4/VeinMining#51]
### Minecraft Version

1.18.1

### What happened?

cant find the config file in defaultconfig and config

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Forge - 40.0.34

### Mod Version

veinmining-forge-1.18.2-0.18

### Relevant Log Outputs

![image](https://user-images.githubusercontent.com/104714626/166139220-136eba8f-cf76-4d94-a347-2f7cfc02a725.png)
![image](https://user-images.githubusercontent.com/104714626/166139242-8bf8509d-2d24-4516-9810-ab997922a198.png)

**Comment by TheIllusiveC4** [comment]
The config file is in your world folder's `serverconfig` folder.
