### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RichPrune** [TheIllusiveC4/VeinMining#61]
### Minecraft Version

1.18.2

### What happened?

the "require blocks to be effective to vein mine" button doesnt work

### How do you trigger this bug?

1.put vein mine on a pick
2.toggle yes on the option
3.still be able to vein mine dirt
...

### Loader

Fabric

### Loader Version

.14.9

### Mod Version

0.0.13

**Comment by TheIllusiveC4** [comment]
This is the intended behavior. By "effective", it means tools that are able to yield drops from the block. A pickaxe can still harvest dirt from dirt blocks, so it still works. However, for example, a stone pickaxe cannot harvest Redstone Ore and it will not vein mine those blocks.
