### ISSUE TITLE
Crash on 1.19.2 fabric again

### ISSUE THREAD

**Issue by Thelegendking** [TheIllusiveC4/VeinMining#64]
### Minecraft Version

1.19.2

### What happened?

Latest build of mod crashed again on 1.19.2 fabric the same way I previously reported 1 or 2 days ago, I also tried to launch the mod by deleting previous config file so that it maybe the reason crash was happening because of old config but no it still crashed.

I understand the mod is in beta so crashes are obvious unless I have a mod that is conflicting with it somehow if that's the case please take your time and do tell I'll remove it, this is one of my favorite mod that I always have in my game. Take care and Thank you.

### How do you trigger this bug?

1.Open the game
2.Mojang screen for a second
3.Then crash
...

### Loader

Fabric

### Loader Version

fabric-loader-0.14.9-1.19.2 w/ fabric-api-0.61.0+1.19.2

### Mod Version

veinmining-fabric-1.0.0-beta.3+1.19.2

### Relevant Log Outputs

[crash-2022-09-22_18.09.43-client.txt](https://github.com/illusivesoulworks/veinmining/files/9625880/crash-2022-09-22_18.09.43-client.txt)

**Comment by TheIllusiveC4** [comment]
This is a different crash from FerriteCore and it doesn't seem to be related to Vein Mining. Does it stop crashing if you remove either mod?

Also, it seems like you have FerriteCore 4.2.1 which is listed as for 1.18.2 even though you're on 1.19.2. So try updating that mod and see if that resolves the crash.

**Comment by Thelegendking** [comment]
Okay so I redownloaded the latest FerriteCore 5.0.0 and launched it with Vein Mining and it crashed again but when I removed the FC mod it didn't crashed.

And when I remove VM mod and launched with FC mod it doesn't crash... also for some reason FC's version is different in game as you can see here I hope :
![Ferrite](https://user-images.githubusercontent.com/89863459/191857809-a8eb4bc5-4fe2-4754-b75d-0fadbb75c660.png)

Isn't there a way to run these two mods together? There was no problem when I was using both of these mod's 1.18.2 build together in 1.18.2 modpack.

**Comment by Thelegendking** [comment]
It seems there is a compatibility problem with them, they seem to run perfectly fine when only one of these two mods (FerriteCore & VeinMining) are in modpack.

**Comment by TheIllusiveC4** [comment]
Hm, weird issue. I can reproduce this, I just don't know what's causing this to happen between these two mods. I'll investigate this a bit.

**Comment by TheIllusiveC4** [comment]
For now, while I investigate this, I've found that a suitable workaround is to go into the `config` folder, and edit `ferritecore.mixins.properties` so that `modelResourceLocations = false`. This will allow the game to run without crashing when both mods are together.

**Comment by Thelegendking** [comment]
Its okay take your time I would rather wait for the new VM build, I try to stay away from performance mod's config files as much as I can who knows that might cause some performance issues you know.
