### ISSUE TITLE
[Bug]: veinmining.json5 is not generating in config

### ISSUE THREAD

**Issue by CobyPruder** [TheIllusiveC4/VeinMining#65]
### Minecraft Version

1.19.2

### What happened?

veinmining.json5 isn't generating in my config folder, but the 3 .toml files for the forge version are. I have the cloth config api installed. 

### How do you trigger this bug?

1.installed cloth config api
2.checked config folder
3.
...

### Loader

Fabric

### Loader Version

fabric .14.9 fabric api 4.11

### Mod Version

1.0.0-beta.3+1.19.2.jar

**Comment by CobyPruder** [comment]
thank you in advance :~)

**Comment by TheIllusiveC4** [comment]
This is working as intended. 1.19.2 on Fabric has toml configuration files, same as Forge now.
