### ISSUE TITLE
[Bug]: Crash on Quilt 1.19.2 server

### ISSUE THREAD

**Issue by Touch-Night** [TheIllusiveC4/VeinMining#69]
### Minecraft Version

1.19.2

### What happened?

Server failed to launch
Error loading class: draylar/magna/api/MagnaTool (java.lang.ClassNotFoundException: draylar/magna/api/MagnaTool)

### How do you trigger this bug?

1. install veinmining server side
2. launch server

### Loader

Fabric

### Loader Version

Quilt-0.17.5-beta2/quilted-fabric-api-4.0.0-beta.12+0.61.0-1.19.2

### Mod Version

veinmining-fabric-1.0.0-beta.5+1.19.2

**Comment by TheIllusiveC4** [comment]
This is not a Vein Mining error, at least not from this:

> Error loading class: draylar/magna/api/MagnaTool (java.lang.ClassNotFoundException: draylar/magna/api/MagnaTool)

It looks like some mod is trying to access a library that you don't have installed, probably called Magna? If you don't have Magna installed, then install it. Or find the mod that is trying to access this library and see if there are any instructions for doing so.

If you attach the full crash log then that might provide further information if you are still stuck.
