### ISSUE TITLE
[Suggestion] Add a keybind for VeinMining activation. (config option for sneak or keybind.)

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/VeinMining#7]
Title^

A QOL addition.

**-** Gbergz

**Comment by 64thParaDux** [comment]
This would save manya bases and also many poor souls from falling into lava. I approve!

**Comment by TheIllusiveC4** [comment]
So how would this work in practice? Would it only work while you are holding down the keybind, or would you use the keybind to activate/deactivate the behavior?

**Comment by Gbergz** [comment]
While you're holding down the keybind.

**Comment by TheIllusiveC4** [comment]
Is there much difference between this proposed keybind and the current configuration option that allows you to activate it only while sneaking? It's very similar to having a keybind, it's just that it's also tied to sneaking.

I'm mainly asking that because making an actual keybind for this is trickier than it sounds and I'm not sure solely being able to choose a different keybind than sneaking is enough benefit to justify the extra overhead involved.

**Comment by Gbergz** [comment]
The problem with sneak activation is that sometimes you justwanna sneak to reach and mine something without falling off a block, or you're just sneaking while mining to be safe and to not fall in lava etc. And when you do that you accidentally activate Vein Mining without thinking about it(done it multiple times already).

That can be very annoying. That's why choosing a different keybind can be very helpful.

Hope this helps.

**Comment by 64thParaDux** [comment]
No one likes to crouch and delete half there base when they just didn't want to fall.

**Comment by zanecek** [comment]
Vein mining while pressing the optional key instead of pressing shift is an excellent improvement, I vote for!

**Comment by TheIllusiveC4** [comment]
Just a quick update, I have decided on implementing this feature. I just need to find the time to do it since it's somewhat non-trivial.

**Comment by TheIllusiveC4** [comment]
Heads up for those on the Forge version:

Because of the changes needed to accomplish this smoothly, the `activationState` config option has been moved to a new client-side configuration file `veinmining-client.toml`. It's located in the `configs` folder in the root folder.
