### ISSUE TITLE
[Bug]: "Require effective tool" does not work

### ISSUE THREAD

**Issue by michelle-blackmore** [TheIllusiveC4/VeinMining#70]
### Minecraft Version

1.18.2

### What happened?

"Require effective tool" does not work - I assume the intended effect is for tools to only be able to vein-mine blocks they are intended for (eg. axe for wood), however I can use my vein mining pickaxe to veinmine logs.

### How do you trigger this bug?

Enable "Require effective tool" in the config for the world you want to play. For me, I did it through the "Configurable" menu which edits config files, but I made sure and it changes it in the txt as well. The issue persists after restarting the game and it still appears toggled on in the menu.

![2022-10-12_21 38 43](https://user-images.githubusercontent.com/24193853/195443197-738130be-1aaa-487e-96a6-4d7988c246d8.png)

### Loader

Forge

### Loader Version

40.1.73

### Mod Version

1.18.2-0.19

**Comment by TheIllusiveC4** [comment]
This is not a bug, at least not from what you've described. Require Effective Tool means tools that are able to harvest the block's drops. For instance, a Stone Pickaxe enchanted with Vein Mining cannot harvest Redstone Dust from a Redstone Ore. When Require Effective Tool is on, it will not proceed to vein mine all of the connected Redstone Ore. When it is off, it will.
