### ISSUE TITLE
Cannot find enchantment "name" for Enchancment compatibility

### ISSUE THREAD

**Issue by MecaZillaFox** [TheIllusiveC4/VeinMining#71]
### Minecraft Version

1.19.2

### What happened?

Simply put, I can't find the code name (like minecraft:looting) for the enchantment so that I can allow it through the configs of the Enchancment mod (since that mod default disables all enchantments not included in the mod).

May I kindly as what the name is and where I could find it in the future?

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric 0.40.1

### Mod Version

1.0.0 beta

**Comment by TheIllusiveC4** [comment]
It seems you've closed this on your own, did you find what you were looking for?

For future reference to you or anyone else looking at this issue, it's `veinmining:vein_mining`.

To find it, you can always look at the [language file](https://github.com/illusivesoulworks/veinmining/blob/1.19.x/common/src/main/resources/assets/veinmining/lang/en_us.json):
```json
{
  "enchantment.veinmining.vein_mining": "Vein Mining",
  "enchantment.veinmining.vein_mining.desc": "Breaks matching connected blocks when mining.",
  "key.veinmining.category": "Vein Mining",
  "key.veinmining.activate.desc": "Activate"
}
```
The name is always the `enchantment` and then the namespace and then the name itself.
