### ISSUE TITLE
[Bug]: vein mining

### ISSUE THREAD

**Issue by Legend77s** [TheIllusiveC4/VeinMining#72]
### Minecraft Version

1.19.2

### What happened?

vein mining is not working

### How do you trigger this bug?

vein minging does not work

### Loader

Forge

### Loader Version

C:\Users\Admin\curseforge\minecraft\Instances\Better Minecraft [FABRIC] - 1.18.2

### Mod Version

c:\Users\Admin\curseforge\minecraft\Instances\Better Minecraft [FABRIC] - 1.18.2\mods\veinmining-fabric-1.0.0-beta.5+1.19.2.jar

### Relevant Log Outputs

» GitHub Gist

**Comment by TheIllusiveC4** [comment]
I'll need some more information. What have you tried and what isn't working? Please list out your steps precisely.

Also, it seems you're running the 1.19.2 version in a 1.18.2 instance? Your folder is named 1.18.2. Is that just a misnomer or do you have the wrong version installed?
