### ISSUE TITLE
[Bug]: "requireEffectiveTool = true" does not work

### ISSUE THREAD

**Issue by armorlight** [TheIllusiveC4/VeinMining#73]
### Minecraft Version

1.19.2

### What happened?

With the config set to vein mine without the enchantment, "requireEffectiveTool = true" does not seem to do anything. Blocks can be vein mined with any item in the hand or just a fist. Using an ineffective tool to vein mine a block that requires an effective tool to drop an item, such as diamond ore, cause the entire vein to disappear.

The issue persists when using either whitelist or blacklist, and regardless of using a keybind or crouching.

maxBlocksBase = 64

maxDistanceBase = 15

### How do you trigger this bug?

1. Set maxBlocksBase and maxDistanceBase to >1 to enable vein mining without enchantment.
2. Use keybind or crouch to vein mine any whitelisted or non-blacklisted block.

### Loader

Fabric

### Loader Version

fabric-loader-0.14.9-1.19.2

### Mod Version

veinmining-fabric-1.0.0-beta.5+1.19.2.jar

**Comment by TheIllusiveC4** [comment]
> Blocks can be vein mined with any item in the hand or just a fist.

This is irrelevant to the config option. If the block can be mined (items are dropped from it), then it doesn't matter if it's with an item or a fist, it will be vein mined if vein mining is active.

> Using an ineffective tool to vein mine a block that requires an effective tool to drop an item, such as diamond ore, cause the entire vein to disappear.

This, however, shouldn't be happening. It should stop at the single source block. I'll test this interaction and get back to you.
