### ISSUE TITLE
[Bug]: Missing data in fabric.mod.json file

### ISSUE THREAD

**Issue by spunchbop121** [TheIllusiveC4/VeinMining#75]
### Minecraft Version

1.19.2

### What happened?

![image](https://user-images.githubusercontent.com/64424996/209409671-b61f04ab-6617-4d91-9812-118ab58d8238.png)

![image](https://user-images.githubusercontent.com/64424996/209409681-e3390fa2-3119-4d94-9bae-010d1268209f.png)

### How do you trigger this bug?

launch doesn't occur until the end due to an empty fabric.mod.json file.

The version affected by the bug: https://www.curseforge.com/minecraft/mc-mods/vein-mining-fabric/files/4239189

### Loader

Fabric

### Loader Version

*

### API Version

*

### Mod Version

veinmining-fabric-1.0.0+1.19.2

**Comment by TheIllusiveC4** [comment]
Did you download the correct file? Because downloading that exact file, the `fabric.mod.json` is populated as expected.
