### ISSUE TITLE
[Bug]: Vein miner not working on Better MC fabric

### ISSUE THREAD

**Issue by LtSZECHUAN** [TheIllusiveC4/VeinMining#78]
### Minecraft Version

1.19.2

### What happened?

I've gone through the config, but no matter what I change the vein miner doesn't work without the enchantment regardless of config settings. I don't know what to do as none of the other solutions actually give directions they simply say "go to config". 
I've also tried this with an isolated version of the mod (with the other things needed to run it), the same config, and the same issue.

### How do you trigger this bug?

Exist.

### Loader

Fabric

### Loader Version

Fabric-0.14.12

### API Version

idk

### Mod Version

veinmining-fabric-1.0.2+1.19.2

### Relevant Log Outputs

N/A

**Comment by TheIllusiveC4** [comment]
What did you change about your config/what does your config look like currently? What have you tried to change? And have you referred to this already: https://github.com/illusivesoulworks/veinmining/wiki/Configuration#popular-settings ?

**Comment by LtSZECHUAN** [comment]
Just the activation type and range, ive reset both with a reinstall since.  And yes. Still only works with the enchantment regarless of the activation type i use.

**Comment by TheIllusiveC4** [comment]
Can you share the contents of your configuration file from your `config` folder? There should be three together, `veinmining-client.toml`, `veinmining-common.toml` and `veinmining-server.toml`.

**Comment by TheIllusiveC4** [comment]
> Still only works with the enchantment regarless of the activation type i use.

If you mean the activation config in the `veinmining-client.toml` file, that won't change if it works with the enchantment or not. As referenced in the wiki page, you need to change `maxBlocksBase` and `maxDistanceBase` in the `veinmining-server.toml` file. Am I correct to assume you've already tried the latter when you mentioned changing the range?

**Comment by LtSZECHUAN** [comment]
I am so sorry to waste your time as I did
I forgot to save my changes. I feel stupid. Everything works fine, i just never saved the file. 
Im sorry
