### ISSUE TITLE
[Bug]: Fabric Config File Missing

### ISSUE THREAD

**Issue by mike1000195** [TheIllusiveC4/VeinMining#81]
### Minecraft Version

1.19.3

### What happened?

config files for forge were populated in root config folder (toml), there is no veinminer.json5 file in the config root of server config file. playing fabric and not able to change the config to allow veinmining to be enabled with a keybind, obviously because there is no config to edit

### How do you trigger this bug?

1. install veinminer
2. try to edit fabric config
3. Error 404: config not found
...

### Loader

Fabric

### Loader Version

0.14.13

### API Version

0.72.0

### Mod Version

1.0.1-1.19.3

**Comment by TheIllusiveC4** [comment]
Since 1.19, the Fabric version also uses the `toml` files. Use those configuration files now instead.

**Comment by mike1000195** [comment]
ah, that wasn't in the wiki i dont believe. thank you for the update.

still have a weird issue going on though, and the reason i was even looking for the fabric version is because i have the server.toml configured now with the block distances, and the activation method for no-enchantment is still set to keybind. however, when mining a block and either pressing/holding the assigned keybind, it does not work. the mod works perfectly fine with the enchantment, but not the keybind whatsoever.

**Comment by TheIllusiveC4** [comment]
Do you mean that the vein mining only works when you have the enchantment? Or that it always works, even without the keybind?

Can you share your configuration files?

**Comment by mike1000195** [comment]
Veinmining does not work with the keybind at all, it does work with the enchantment though. The people on the sever dont want to use the enchantment, they want to use the keybind. ill upload the config files for you

**Comment by mike1000195** [comment]
Client: https://pastebin.com/54eEmbBR
Common: https://pastebin.com/GUkTi1hs
Server: https://pastebin.com/mTwtWNPE

**Comment by mike1000195** [comment]
EDIT: nevermind, when i edited the server config the last time for the block number and distance last time, i did it with the server running when i saved it. when i restarted the server, it changed them back to 0. had to set the parameters first, then start the server.

my bad lol, thanks again.
