### ISSUE TITLE
[Bug]: Veinminer config missing from server files.

### ISSUE THREAD

**Issue by Nicole-Evermore** [TheIllusiveC4/VeinMining#82]
### Minecraft Version

1.19.2

### What happened?

I have installed a server with the 1.19.2 fabric version of the mod. However, no-where in the config folders anywhere in the server architecture has a corresponding json5 config been generated, that I can find.

### How do you trigger this bug?

I installed a server with an instance of the 'Better Minecraft' fabric pack. I cannot locate the proper config json5 file.

### Loader

Fabric

### Loader Version

Fabric Loader 0.14.12-1.19.2

### Mod Version

v1.0.2+1.19.2

**Comment by Nicole-Evermore** [comment]
Note that the 3 .toml files forge uses do show up in the root configs folder.
![image](https://user-images.githubusercontent.com/40040673/217391153-1887ab28-bb8b-48ce-afca-27527c595a57.png)

**Comment by TheIllusiveC4** [comment]
Starting with 1.19, the `toml` files are used for configuration on Fabric as well.

**Comment by Nicole-Evermore** [comment]
> Starting with 1.19, the `toml` files are used for configuration on Fabric as well.

Ah, then that's not reflected in the Configuration section of the wiki. Could you please tell me how to enable Vein Mining without requiring the enchantment then?

**Comment by TheIllusiveC4** [comment]
Yeah, I need to update the documentation, it's just weird with different versions having different info so I've been trying to setup an alternative solution.

To enable it without requiring the enchantment, you can follow the same instructions as Forge on the Configuration section. Namely, change these values in `veinmining-server.toml`:
```toml
maxBlocksBase = 50
maxDistanceBase = 15
```

**Comment by Nicole-Evermore** [comment]
Thank you very much!

**Comment by Nicole-Evermore** [comment]
New issue, something is re-setting the server config file back to its default state after my server re-starts. Any ideas?
