### ISSUE TITLE
[Bug]: Mod is causing crash on startup

### ISSUE THREAD

**Issue by alsoGAMER** [TheIllusiveC4/VeinMining#83]
### Minecraft Version

1.19.2

### What happened?

Mod is causing crash on startup, Caused by: 

```java
java.util.ServiceConfigurationError: com.illusivesoulworks.veinmining.common.platform.services.IPlatform: com.illusivesoulworks.veinmining.platform.FabricPlatform Unable to get public no-arg constructor
```

### How do you trigger this bug?

Just start the server

### Loader

Fabric

### Loader Version

0.14.12

### API Version

0.73.2+1.19.2

### Mod Version

1.0.2+1.19.2

### Relevant Log Outputs

https://pastebin.com/PzYyVfKd

**Comment by TheIllusiveC4** [comment]
That's an odd error, I've never seen that before and I can't find much information on it. I also can't reproduce it, as the mod with your listed version numbers works fine for me.

Can you verify that you're using Java 17 and not an outdated version? If you're not sure, you can try redownloading/reinstalling Java. In addition, try redownloading the mod and make sure it's the correct file and not the sources file or anything like that.

**Comment by alsoGAMER** [comment]
Sorry for the late reply, issue is caused when incompatible mods are present into mods folder (happened twice with tabtps).

Closing
