### ISSUE TITLE
[Bug]: Veinminer doesn't deactivate

### ISSUE THREAD

**Issue by Domgee504** [TheIllusiveC4/VeinMining#84]
### Minecraft Version

1.19.3

### What happened?

I binded a key to veinminer, pressed a key and now it's not able to turn off. Couching makes it mine normally but standing veinmines . I've tried messing with the config to no avail. Reloading the game also does no good.

### How do you trigger this bug?

1. Press the veinminer activation key

### Loader

Fabric

### Loader Version

Fabric 0.14.14

### Mod Version

Vein Mining v1.0.2+1.19.2

**Comment by TheIllusiveC4** [comment]
It sounds like your config isn't actually set to use the activation key. When you go into `veinmining-client.toml`, what do those values say? If you're using the enchantment, which is true by default, then you need to see what the `activationState` field says. If it says "STANDING", then that means you will vein mine when you have the enchantment and you're standing, and you won't when you're crouching. Which sounds like the behavior you're describing.

If you want to press a key instead, you need to change that value to "KEYBINDING".
