### ISSUE TITLE
[Feature]: Right click Support for things like mass log stripping 

### ISSUE THREAD

**Issue by RCertainty** [TheIllusiveC4/VeinMining#86]
### What is the new feature or improvement?

I have veinmine on a axe and am trying to build a large structure that requires stacks on stacks of stripped logs, it is incredibly painful to strip every single one, I would love it if you can make it so I could mass strip the logs with my axe. 

It would make everything so much less time consuming.

**Comment by TheIllusiveC4** [comment]
Originally I thought this would be good to add, but I've ultimately decided against it.

Currently the behavior for vein mining is very simple to understand, which is that it is able to break matching connected blocks. However, adding support for _using_ the item on multiple connected blocks opens up a whole new branch of potential usages and questions about its functionality that I think over-complicate the design.

If players realize that they can use this for mass log-stripping, then they'll begin to question why they can't use it for other purposes. Why not be able to use shovels to mass dig paths? Or use a hoe to mass produce farmland? While these all might be neat ideas, they just open up too many potential concerns for my liking, not to mention needing to account for all the potential modded interactions that could come up.
