### ISSUE TITLE
[Bug]: Crash with Guard Villagers

### ISSUE THREAD

**Issue by pokesmells** [TheIllusiveC4/VeinMining#88]
### Minecraft Version

1.19.2

### What happened?

When interacting with guard villagers, it crashes immediately.

### How do you trigger this bug?

1. Go to village
2. Move around
3. Crash!
...

### Loader

Fabric

### Loader Version

0.14.17

### API Version

fabric-api-0.75.1+1.19.2

### Mod Version

 veinmining-fabric-1.1.0+1.19.2

### Relevant Log Outputs

https://mclo.gs/Cv6ai3a

**Comment by TheIllusiveC4** [comment]
https://github.com/illusivesoulworks/veinmining/issues/87
