### ISSUE TITLE
[Bug]: client config activatestate"CROUCHING" does not work

### ISSUE THREAD

**Issue by TurtleLurky** [TheIllusiveC4/VeinMining#89]
### Minecraft Version

1.19.2

### What happened?

After downloading the mod (it's very nice btw) and edited the configs to my liking I realized that even when I put "CROUCHING" into the client config so vein miner only activates while sneaking it doesn't work.

### How do you trigger this bug?

1. Download mod
2. Change config active state to "CROUCHING"
3. Notice that vein miner activates while standing, but doesn't while crouching

### Loader

Forge

### Loader Version

Forge 43.2.0

### API Version

N/A

### Mod Version

veinmining-forge-1.0.1+1.19.2.jar

**Comment by TheIllusiveC4** [comment]
Are you editing the configs while in-game? Make sure to edit the configuration files only when out of the game.

If not, which file are you editing and where is it located?

**Comment by TurtleLurky** [comment]
I'm editing the config while the server is stopped, then I restart it to ensure the changes are saved. I don't close MC every time I do this, but I just tried and it still didn't work. 

The file is "veinmining-client.toml" located in the config folder of the server

**Comment by Fabrieze** [comment]
Seconded. I recently moved a server's vein mining over to keybind to avoid accidents, but after a server reboot, notably, the client.toml returns itself to "STANDING" and does not honor anything else typed into it. This is true for both server and client config changes.

My issue however occurs on fabric, if it changes anything, but there is no json global config and instead client/server/common tomls.

**Comment by TheIllusiveC4** [comment]
If you're trying to edit a client configuration file on a dedicated server, then that would be part of the issue. That file won't have any effect if you're editing it on a dedicated server. You need to edit the file on your local client instance folder instead in order for it to take effect.

> This is true for both server and client config changes.

@Fabrieze Do you mean config changes server-side and client-side, OR do you mean changes to `veinmining-client.toml` and `veinmining-server.toml`?

**Comment by Fabrieze** [comment]
> If you're trying to edit a client configuration file on a dedicated server, then that would be part of the issue. That file won't have any effect if you're editing it on a dedicated server. You need to edit the file on your local client instance folder instead in order for it to take effect.
> 
> > This is true for both server and client config changes.
> 
> @Fabrieze Do you mean config changes server-side and client-side, OR do you mean changes to `veinmining-client.toml` and `veinmining-server.toml`?

Ah, your dedicated server comment made it all click in place. I was under the impression that the server config would override client sided ones or globally change it, but keybinding works when editing the client config on solely my end. Sorry for the trouble, and thank you!

**Comment by TurtleLurky** [comment]
Same for me, thank you so much!
