### ISSUE TITLE
whitelisting

### ISSUE THREAD

**Issue by aGingerThing** [TheIllusiveC4/VeinMining#9]
when I try to turn the word from blacklist to whitelist in the config it just disables vein mining any block instead of whitelisting all the blocks that are listed.

**Comment by TheIllusiveC4** [comment]
Please share your config settings.

**Comment by TheIllusiveC4** [comment]
I've also just tested this myself and can confirm that the whitelisting configuration option is working as expected.

**Comment by aGingerThing** [comment]
https://pastebin.com/iSzDyaJV there is the config content

**Comment by TheIllusiveC4** [comment]
```
// List of whitelisted/blacklisted blocks or block tags
"blocks": [ 
],
```

Your whitelisted blocks are empty, so that's why it's not applying to anything.

**Comment by aGingerThing** [comment]
did work. this is what I changed it too https://pastebin.com/SMkyMT8z

**Comment by TheIllusiveC4** [comment]
Yes, you have to wrap each entry in quotation marks.

Example:
```
"blocks": ["minecraft:iron_ore", "minecraft:diamond_ore"],
```

**Comment by aGingerThing** [comment]
Thanks, it worked, and thank you for helping.

**Comment by aGingerThing** [comment]
Thanks, it worked, and thank you for helping.
