### ISSUE TITLE
[Bug]: Unexpected behaviour with Vein Mining + breaking Ice

### ISSUE THREAD

**Issue by Nitjsefnie** [TheIllusiveC4/VeinMining#90]
### Minecraft Version

1.19.3

### What happened?

Expected behaviour: every ice mined with a non-silk touch pickaxe should get replaced with water
What happened:
![2023-03-11_10 48 54](https://user-images.githubusercontent.com/75166987/224477495-c6d61d24-9c43-41e8-ad3d-28981d49078b.png)

### How do you trigger this bug?

1. Hit ice with Vein Mining
2. Observe

### Loader

Fabric

### Loader Version

0.14.14

### API Version

0.75.1

### Mod Version

1.0.1-1.19.3

**Comment by TheIllusiveC4** [comment]
You're using an outdated version, 1.0.1. Please update to the latest version, 1.1.1, and this issue should be resolved.
