### ISSUE TITLE
[Bug]: vein mining not working [mc better 1.19.2 fabric ]

### ISSUE THREAD

**Issue by kysne** [TheIllusiveC4/VeinMining#91]
### Minecraft Version

1.19.2

### What happened?

i really dont why but mine veining is not working. i have this enchantment on my pickaxe and no matter what(crouching, standing)
allways break only one block. i tried making another with vein minng but this one was not wotrking to. i tried to redowlnd but still nothing changed (sorry for my english)
pls help :(

### How do you trigger this bug?

always mining only one block

### Loader

Fabric

### Loader Version

im using curse forge 

### API Version

curse forge!

### Mod Version

v1.1.1+1.19.2

### Relevant Log Outputs

-f

**Comment by lilqchi** [comment]
yo i had the same promblem all u need is go to curseforge click 3 dots on the right at better mc modpack next open folder next find config folder and look for veinmining-client.toml open it with notepad and activationState change from KEYBINDING to STANDING or CROUCHING (CROUCHING is better imo).

**Comment by kysne** [comment]
bro thank you so much, im new in mods and i ddint think about config 
tytytytytyty
<333
(now is working)
ty again

**Comment by lilqchi** [comment]
np bro have a nice day 😁
