### ISSUE TITLE
[Suggestion]: Relocate drops relocates xp also

### ISSUE THREAD

**Issue by Nitjsefnie** [TheIllusiveC4/VeinMining#92]
### What is the new feature or improvement?

This would be useful when vein mining sculk for example

**Comment by TheIllusiveC4** [comment]
This should already be the case. What version of MC and Vein Mining are you running?

**Comment by Nitjsefnie** [comment]
1.19.3 & 1.1.1

**Comment by TheIllusiveC4** [comment]
Fabric or Forge?

**Comment by Nitjsefnie** [comment]
Fabric
