### ISSUE TITLE
[Bug]: Mixin Conflict with Carpet Additions on latest ver

### ISSUE THREAD

**Issue by itsdinkd** [TheIllusiveC4/VeinMining#93]
### Minecraft Version

1.19.2

### What happened?

Updated vein mining to 1.1.1 and it now conflicts with Carpet TIS additions causing a crash on dedicated server on launch

the version before 1.1.1 worked fine.

### How do you trigger this bug?

1. Get vein mining 1.1.1
2. Add Carpet, and Carpet TIS additions
3. crash
...

### Loader

Fabric

### Loader Version

0.14.18

### Mod Version

1.1.1

### Relevant Log Outputs

https://pastebin.com/7ZPbUnCC

**Comment by TheIllusiveC4** [comment]
Have you tried with _only_ Vein Mining and Carpet + Carpet TIS installed? Also, does this occur on clients as well?

**Comment by itsdinkd** [comment]
Nope. Only because this happened only when I updated vein mining.

It didn't happen on client.

**Comment by itsdinkd** [comment]
Alright, put it in a testing environment with just carpet / this additions and vein mining 1.1.1 and it **did not** crash.

There's some other mod here in the middle causing issues.
