### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by eyebullz** [TheIllusiveC4/VeinMining#94]
### Minecraft Version

1.16.5

### What happened?

I run a modded pixelmon server for me and some friends, and our vein miner only works randomly. I've gone through a full unbreaking 3 diamond pick and have seen vein mining actually happen no more than 15 times. The blacklist is on in the config, so no blocks are restricted, and the mod works perfectly fine in singleplayer. I've tried using a previous version, different activation modes, but to no avail. Mod list below.
![Screenshot 2023-04-17 173851](https://user-images.githubusercontent.com/131090820/232639662-e8744acf-39b6-4af4-8ebd-8ce0ac8215bc.png)

### How do you trigger this bug?

1. Enchant any pickaxe or tool with vein mining
2. Hold down the activation key in the settings, or crouch, depending on what activation state
3. Attempt to mine wood, stone, ores, anything
4. Fail to vein mine majority of the time
...

### Loader

Forge

### Loader Version

Forge - 36.2.34

### API Version

N/A

### Mod Version

Vein Mining 1.16.5 - 0.12

**Comment by TheIllusiveC4** [comment]
I'll need to see the configuration files, both the `veinmining-client.toml` in your client's `config` folder AND the `veinmining-server.toml` in your server's `world > serverconfig` folder.

Also, I noticed you have a `plugins` folder. Are you using a hybrid server and not a Forge one?

**Comment by eyebullz** [comment]
[veinmining-client.txt](https://github.com/illusivesoulworks/veinmining/files/11268418/veinmining-client.txt)

 
[veinmining-server.txt](https://github.com/illusivesoulworks/veinmining/files/11268421/veinmining-server.txt)

TBH, there isn't anything in the plugins folder and I just forgot to delete it. It is definitely a forge server

**Comment by TheIllusiveC4** [comment]
Nothing seems wrong with the configuration files. So let's try a few things:

1. Update your Vein Mining to the latest version, which on 1.16.5 should be 0.18. You're currently on a fairly outdated version.
2. If the above doesn't change anything, then are there any mods that exist on the server that you do not have on your client or vice versa?
3. Also, share your log files from a session where you attempt to vein mine something.
