### ISSUE TITLE
[Bug]: Mining multiple wooden planks

### ISSUE THREAD

**Issue by Pastole** [TheIllusiveC4/VeinMining#95]
### Minecraft Version

1.19.3

### What happened?

I tried to take out 1 block of a wooden plank from a structure I built. When I did that, it ended up removing about 1/2 the room of wooden planks. I don't want vein mining to work on any planks, only trees and ores. 
Also, I'm on 1.19.4 but that wasn't an option in the dropdown menu for minecraft version

### How do you trigger this bug?

1. Used netherite axe to remove 1 plank
2. Several planks were removed instead of 1
3.
...

### Loader

Fabric

### Loader Version

Fabric

### API Version

Fabric-api-0.78.0+1.19.4.jar

### Mod Version

veinmining-fabric-1.12+1.19.4jar

**Comment by TheIllusiveC4** [comment]
This is not a bug, the default behavior is that it works on any blocks. If you want to configure it to only work on logs and ores, then please look into your `config` folder, find `veinmining-server.toml` and adjust the settings like so:  `blocksPermission = "WHITELIST"` and `blocks = ["#c:ores", "#minecraft:logs"]`.

Find more details about the configuration here: https://github.com/illusivesoulworks/veinmining/wiki/Configuration

**Comment by tomocrafter** [comment]
seems like blocksPermission is not in config, there is blocksList and groupsList instead.
I don't understand what is the difference between those two and have no Idea to do same thing as this issue with those new options. Could you update the wiki for new options?

Edit:
I removed all from groupsList and added to blocksList, and made blocksListType to ALLOW and it works as expected.
I hope there is new option to `requireCorrectTool` which *only* allows vein mine if mined wood with axe, as well as ore with pickaxe.
