### ISSUE TITLE
[Bug]: Vein mining doesnt activate, i could have an old version tbh

### ISSUE THREAD

**Issue by glkennedy904** [TheIllusiveC4/VeinMining#96]
### Minecraft Version

1.19.2

### What happened?

Vein mining does not work on anything, ores, minerals etc

### How do you trigger this bug?

1.idk
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric

### Mod Version

Vein Mining (Fabric 1.16.4 - 1.19.2)

**Comment by TheIllusiveC4** [comment]
Are you testing it with a tool that has the enchantment?

**Comment by CryoNine** [comment]
> Are you testing it with a tool that has the enchantment?

I have the same issue. I used every type of tool with the enchantment and nothing happens

**Comment by glkennedy904** [comment]
Yes, two different pickaxes

**Comment by TheIllusiveC4** [comment]
Okay, I'll need both of you to provide me with the Vein Mining mod version number, the Fabric API mod version number, and a copy of your configuration files.

In addition, please test to see if this behavior changes when you load _only_ Vein Mining and Fabric API with no other mods.

**Comment by minhperry** [comment]
I also have the same bug, come with BetterMC Fabric modpack, mod version v1.1.1-1.19.2

**Comment by TheIllusiveC4** [comment]
> I also have the same bug, come with BetterMC Fabric modpack, mod version v1.1.1-1.19.2

Looking at the modpack, it seems they configured it to activate via keybinding. Have you set the keybinding for the vein mining activation and are you holding it down while mining with a Vein Mining pickaxe/tool?

**Comment by Onipotencia** [comment]
> > I also have the same bug, come with BetterMC Fabric modpack, mod version v1.1.1-1.19.2
> 
> Looking at the modpack, it seems they configured it to activate via keybinding. Have you set the keybinding for the vein mining activation and are you holding it down while mining with a Vein Mining pickaxe/tool?

I downloaded this modpack today and I happen to have the same problem, I press the hotkey and nothing happens with the ores, it only happens with the trees.

**Comment by TheIllusiveC4** [comment]
> I press the hotkey and nothing happens with the ores, it only happens with the trees.

Better MC has it configured to work with everything, not just ores and trees. Have you tried other blocks? Which ore did you test it on?

I just downloaded the modpack and tested it myself, everything with the default configs works as expected. Please follow my steps here and tell me if you are experiencing something different:

1) Make sure all configs, mods, and keybinding are default that comes with Better MC Fabric 1.19.2 v18.5. If they are not default, be sure to understand what changes were made and list them in this issue report accordingly.
2) Start a new world.
3) Give yourself a vanilla Diamond Pickaxe.
4) Enchant the pickaxe with `"veinmining:vein_mining"`.
5) Place a row of vanilla Diamond Ore blocks.
6) **Hold down** `` ` ``, the default keybinding for vein mining, while mining the Diamond Ore.

Following those steps, I was able to successfully vein mine a row of Diamond Ore as expected. If you are experiencing something different with those exact steps, then please let me know and list your own steps as detailed as possible.

**Comment by ghost** [comment]
> > 我按下热键，矿石没有发生任何反应，只发生在树木上。
> 
> Better MC 的配置可以处理所有东西，而不仅仅是矿石和树木。您尝试过其他块吗？你测试的是哪种矿石？
> 
> 我刚刚下载了 modpack 并亲自测试了它，默认配置的所有内容都按预期工作。请按照此处的步骤进行操作，并告诉我您是否遇到了不同的情况：
> 
> 1. 确保所有配置、模组和键绑定都是 Better MC Fabric 1.19.2 v18.5 附带的默认设置。如果它们不是默认的，请务必了解所做的更改并相应地在此问题报告中列出它们。
> 2. 开始一个新世界。
> 3. 给自己一把香草钻石镐。
> 4. 用 为镐附魔`"veinmining:vein_mining"`。
> 5. 放置一排香草钻石矿石块。
> 6. **** `` ` ``开采钻石矿石时，**按住，这是矿脉开采的默认键绑定。**
> 
> 按照这些步骤，我能够按预期成功地开采一排钻石矿石。如果您在执行这些具体步骤时遇到了不同的情况，请告诉我并尽可能详细地列出您自己的步骤。

yes i do all lot this but it didn't work! forge 1.20.1
