### ISSUE TITLE
[Bug]: Whenever I open a world, the config files reset

### ISSUE THREAD

**Issue by Q01010001** [TheIllusiveC4/VeinMining#98]
### Minecraft Version

1.19.2

### What happened?

I changed the client config file to have vein mining only when I'm crouching, using all uppercase as is displayed for one of the options, then I hit save and close it. Then when I load into a world, all 3 config files have the current time as when they were last modified and they reset to the defaults. I tried closing the game and relaunching, but that didn't fix the issue. I don't know if I'm doing something wrong to have the configs properly save and load, but I think I'm doing things correctly.

### How do you trigger this bug?

1. Change the config
2. Save and close
3. Reload the game and open a world

### Loader

Forge

### Loader Version

Forge - 43.2.0

### Mod Version

1.1.1 I think. Latest Release as of July 4th

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, the config saves normally on my end. Please share your config file that you're trying to save, usually resetting means that your syntax is incorrect. Are all of the config files resetting or just the one you changed? If all of them are resetting, please share those config files as well and the values that were changed.

**Comment by JaredAI** [comment]
This also happens to me. 

Go to veinmining-client.toml, select "crouching" for both options, click done and it will work during that session. Exit minecraft, start a new session, and while the config file still shows "crouching" it will vein mine while NOT crouching (it uses the default config). Go back into the config and cycle through the options to again select "crouching" and upon returning to the game it will now act correctly.

**Comment by TheIllusiveC4** [comment]
Are you also on 1.19.2? What do you mean by "cycling" through the options? Does it say "CROUCHING" or "crouching"? Are you editing the config file while outside of the game?

**Comment by JaredAI** [comment]
> Are you also on 1.19.2? What do you mean by "cycling" through the options? Does it say "CROUCHING" or "crouching"? Are you editing the config file while outside of the game?

I'm on 1.20 Fabric. 

Modmenu has an interface that has 3 options for veinmining:

Veinmining-common.toml
Veinmining-client.toml
Veinmining-server.toml

When clicking on Veinmining-client.toml button it gives you another button with 3 options: STANDING, CROUCHING, HOLD_KEY_DOWN

When CROUCHING is selected, it works until the game is exited and then during a new game it'll revert to the default configuration. 

I just edited the Veinmining-client.toml file directly and it works as expected. So maybe this is an issue with modmenu?

**Comment by TheIllusiveC4** [comment]
> I just edited the Veinmining-client.toml file directly and it works as expected. So maybe this is an issue with modmenu?

Based on your explanation, I was able to reproduce this issue and I don't believe it's an issue with Mod Menu. I've yet to figure out the cause, but I'll fix this in the next update. Until then, just edit the configuration files directly when needed.

**Comment by dit-zy** [comment]
This happens to me when I modify the files manually. I tried changing `levels` to 5 in `veinmining-common.toml` on my server, but it got reset back to 1 after restarting the server. Then I tried changing `maxDistancePerLevel` and `maxBlocksPerLevel` in `veinmining-server.toml` and the same thing happened after restarting the server again.

**Comment by TheIllusiveC4** [comment]
Are you trying to edit the files while the server is running? If so, try and edit them while the server is shutdown.

**Comment by dit-zy** [comment]
Oh that did resolve my issue editing the files directly. Thank you!

I'm so used to editing the configs live that I forgot that could cause issues for some mods.
