### ISSUE TITLE
[Bug]:  disabled by configuration on minecraft server

### ISSUE THREAD

**Issue by abysskya** [TheIllusiveC4/VeinMining#99]
### Minecraft Version

1.20.1

### What happened?

I'm new to setting up servers with mods, but i can't seem to find a solution to this.

i got the fabric verson of veinminer 1.20.1 and its disabled by configuration.

i can't seem to type in /veinminer.

what do i do?

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

fabric 1.20.1 (fabric API + Lithium + Phosphor)

### API Version

fabric API newest atm

### Mod Version

1.20.1

**Comment by TheIllusiveC4** [comment]
> i can't seem to type in /veinminer.

You might be confusing this with another vein mining mod. There is no such command in this mod.

> i got the fabric verson of veinminer 1.20.1 and its disabled by configuration.

If you're referring to the keybinding, it just means that the keybinding doesn't work for your configuration. You need to check your `veinmining-client.toml` configuration to see what the default activation method is, which by default is just standing normally while using a tool enchanted with Vein Mining.
